function tests = test_linear_exp_feedback_instrumentation
%TEST_LINEAR_EXP_FEEDBACK_INSTRUMENTATION Verify the schema-v3 signal path.
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
repoRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(fullfile(repoRoot, "src"));
modelFile = fullfile(repoRoot, "simulink", "linear_exp_2025a.slx");
load_system(modelFile);
testCase.TestData.repoRoot = repoRoot;
testCase.TestData.modelName = "linear_exp_2025a";
end

function teardownOnce(testCase)
modelName = testCase.TestData.modelName;
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
end

function testFileWriterHasSeventeenInputsAndPreservesLegacyOrder(testCase)
modelName = testCase.TestData.modelName;
muxPath = modelName + "/Mux1";
writerPath = modelName + "/TwinCAT File Writer";

testCase.verifyEqual(string(get_param(muxPath, "Inputs")), "17");
testCase.verifyEqual( ...
    string(get_param(writerPath, "FunctionName")), ...
    "TcFileWriter");

connectivity = get_param(muxPath, "PortConnectivity");
expectedBlocks = [ ...
    modelName + "/" + sprintf("Trial Length\nCounter"), ...
    modelName + "/Sum", ...
    modelName + "/Quantizer1", ...
    repmat(modelName + "/Linear System", 1, 4)];
expectedPorts = 0:3;

for i = 1:7
    testCase.verifyEqual( ...
        string(getfullname(connectivity(i).SrcBlock)), ...
        expectedBlocks(i), ...
        sprintf("Legacy File Writer input %d changed source.", i));
end
testCase.verifyEqual([connectivity(4:7).SrcPort], expectedPorts);

for i = 8:17
    testCase.verifyEqual( ...
        string(getfullname(connectivity(i).SrcBlock)), ...
        modelName + "/Virtual CST Diagnostics");
    testCase.verifyEqual(connectivity(i).SrcPort, i - 8);
end
end

function testDiagnosticInputsAreTypedAndExplicitlyConvertedToDouble(testCase)
modelName = testCase.TestData.modelName;
subsystem = modelName + "/Virtual CST Diagnostics";
names = [ ...
    "PanasonicPositionRaw", ...
    "PanasonicVelocityRaw", ...
    "PanasonicWcState", ...
    "PanasonicInputToggle", ...
    "CopleyWcState", ...
    "CopleyInputToggle", ...
    "PanasonicStatusWord", ...
    "PanasonicErrorCode", ...
    "TaskCycleTimeExceeded", ...
    "TaskExceedCounter"];
types = [ ...
    "int32", "int32", ...
    "boolean", "boolean", "boolean", "boolean", ...
    "uint16", "uint16", "boolean", "uint32"];

for i = 1:numel(names)
    inputPath = subsystem + "/" + names(i);
    conversionPath = inputPath + "ToDouble";
    testCase.verifyEqual(string(get_param(inputPath, "PortDataType")), types(i));
    testCase.verifyEqual( ...
        string(get_param(conversionPath, "OutDataTypeStr")), ...
        "double");
end
end

function testGeneratedCodeAndTmcExposeSchemaV3(testCase)
generatedRoot = fullfile( ...
    testCase.TestData.repoRoot, "linear_exp_2025a_tcgrt");
headerText = fileread(fullfile(generatedRoot, "linear_exp_2025a.h"));
testCase.verifyNotEmpty(regexp( ...
    headerText, ...
    'TmpSignalConversionAtTwinCATFil\s*\[17\]', ...
    'once'));

tmcText = fileread(fullfile(generatedRoot, "linear_exp_2025a.tmc"));
testCase.verifyNotEmpty(regexp( ...
    tmcText, '<Version>0\.0\.0\.17</Version>', 'once'));
testCase.verifyNotEmpty(regexp( ...
    tmcText, '<Elements>17</Elements>', 'once'));

inputNames = [ ...
    "PanasonicPositionRaw", ...
    "PanasonicVelocityRaw", ...
    "PanasonicWcState", ...
    "PanasonicInputToggle", ...
    "CopleyWcState", ...
    "CopleyInputToggle", ...
    "PanasonicStatusWord", ...
    "PanasonicErrorCode", ...
    "TaskCycleTimeExceeded", ...
    "TaskExceedCounter"];
for name = inputNames
    testCase.verifyNotEmpty(regexp( ...
        tmcText, "<Name>" + name + "</Name>", 'once'), ...
        "Generated TMC input is missing: " + name);
end
end

function testLiveScriptContainsAcquisitionAnalysisAndSaveChain(testCase)
liveScript = fullfile( ...
    testCase.TestData.repoRoot, "exp02_FB", "feedback_experiment.mlx");
convertedScript = fullfile( ...
    tempdir, "feedback_experiment_schema3_static_check.m");
matlab.internal.liveeditor.openAndConvert( ...
    char(liveScript), char(convertedScript));
cleanup = onCleanup(@()localDeleteFile(convertedScript));
scriptText = fileread(convertedScript);

requiredText = [ ...
    "measurement_schema_version ~= uint16(3)", ...
    "panasonic_position_raw_count = measurement(8,:)", ...
    "task_exceed_counter = measurement(17,:)", ...
    "analyze_position_feedback_health(analysis_input)", ...
    '"position_feedback_health"', ...
    '"measurement_time_raw"'];
for text = requiredText
    testCase.verifyNotEmpty(strfind(scriptText, text));
end

issues = checkcode(convertedScript, "-id");
issueIds = string({issues.id});
testCase.verifyFalse(any(issueIds == "PARSE"));
end

function localDeleteFile(path)
if isfile(path)
    delete(path);
end
end
