function tests = test_copley
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
projectRoot = fileparts(fileparts(mfilename('fullpath')));
matlabDir = fullfile(projectRoot, 'src');
addpath(projectRoot);
addpath(matlabDir);
testCase.TestData.ProjectRoot = projectRoot;
testCase.TestData.MatlabDir = matlabDir;
end

function testCommissioningAppliesCalibrationWhenAllProtocolsAccepted(testCase)
[useCase, ports, plan] = localUseCase();
out = useCase.run(plan);

verifyTrue(testCase, out.accepted);
verifyTrue(testCase, out.calibration_applied);
verifyEqual(testCase, ports.motor.StageCount, 2);
verifyEqual(testCase, ports.motor.RegisterCount, 1);
verifyTrue(testCase, ports.motor.RegisteredReference{1}.metadata.accepted);
verifyEqual(testCase, ...
    ports.motor.RegisteredReference{1}.metadata.version, uint16(2));
verifyEqual(testCase, ports.sequencer.StartedProtocols(:)', uint16([1 2 3]));
verifyGreaterThan(testCase, size(ports.sequencer.Heartbeats, 1), 0);
verifyEqual(testCase, numel(ports.store.Results), 1);
end

function testProtocolRejectionStopsBeforeCalibration(testCase)
[useCase, ports, plan] = localUseCase();
existing = struct('axis_index', uint16(1), ...
    'reference_position_count', int32(-1), ...
    'reference_commutation_angle', uint16(2), ...
    'electrical_direction', int16(3));
ports.motor.RegisteredReference{1} = existing;
ports.logger.setProtocolLog(2, struct('protocol_id', uint16(2), ...
    'accepted', false, 'reason', 'forced protocol rejection'));

out = useCase.run(plan);

verifyFalse(testCase, out.accepted);
verifyFalse(testCase, out.calibration_applied);
verifyEqual(testCase, ports.motor.StageCount, 1);
verifyEqual(testCase, ports.motor.RegisterCount, 0);
verifyEqual(testCase, ports.motor.RegisteredReference{1}, existing);
verifyEqual(testCase, ports.sequencer.StartedProtocols(:)', uint16([1 2]));
verifyEqual(testCase, out.rejection_reason, 'forced protocol rejection');
end

function testProtocolOrderCanRunProtocol2Only(testCase)
[useCase, ports, plan] = localUseCase();
plan.protocol_order = uint16(2);

out = useCase.run(plan);

verifyTrue(testCase, out.accepted);
verifyEqual(testCase, ports.sequencer.StartedProtocols(:)', uint16(2));
verifyEqual(testCase, numel(out.protocol_results), 1);
verifyEqual(testCase, out.protocol_results{1}.protocol_id, uint16(2));
verifyEqual(testCase, ports.motor.StageCount, 0);
verifyEqual(testCase, ports.motor.RegisterCount, 1);
end

function testHeartbeatFaultAbortsRun(testCase)
[useCase, ports, plan] = localUseCase();
ports.sequencer.FaultProtocol = uint16(1);
ports.sequencer.FaultAfterPolls = 1;
ports.sequencer.FaultReason = 'heartbeat_expired';

verifyError(testCase, @()useCase.run(plan), ...
    'copley:RunProtocolUseCase:SequencerFault');
verifyGreaterThan(testCase, ports.sequencer.AbortCount, 0);
verifyEqual(testCase, ports.motor.StageCount, 0);
verifyEqual(testCase, ports.motor.RegisterCount, 0);
end

function testCommandRejectionIsReported(testCase)
[useCase, ports, plan] = localUseCase();
ports.sequencer.RejectCommandId = 'prepare_protocol';

verifyError(testCase, @()useCase.run(plan), 'copley:CommandRejected');
verifyEqual(testCase, ports.motor.StageCount, 0);
verifyEqual(testCase, ports.motor.RegisterCount, 0);
end

function testAdsCommandMappingAndDryRun(testCase)
copley_project_root();
client = copley.infra.AdsClient(struct('dryRun', true));
port = copley.infra.AdsSequencerPort(client, struct('timeout_s', 0.1));
plan = copley.domain.defaultExperimentPlan(uint32(77));
specs = copley.protocols.defaultProtocolSpecs();
cmd = copley.domain.command('prepare_protocol', uint32(1001), plan, specs(1));

ack = port.sendCommand(cmd);
mailbox = client.readSymbol('GVL_ExperimentSequencer.command');
params = client.readSymbol('GVL_ExperimentSequencer.protocolParams');

verifyTrue(testCase, ack.accepted);
verifyEqual(testCase, mailbox.command_id, uint16(1));
verifyEqual(testCase, mailbox.request_id, uint32(1001));
verifyEqual(testCase, mailbox.protocol_id, uint16(1));
verifyEqual(testCase, params.axis_index, uint16(1));
verifyFalse(testCase, isfield(mailbox, 'target_current_count'));
verifyFalse(testCase, isfield(mailbox, 'experiment_angle_rad'));
verifyFalse(testCase, isfield(mailbox, 'duration_s'));
verifyFalse(testCase, isfield(mailbox, 'rejection_code'));
removedParams = {'protocol_id', 'tau_e_m', 'x_ref_m', ...
    'theta_offset_guess_rad', 'q_axis_sign', 'electrical_angle_sign', ...
    'x_center_m', 'max_travel_from_start_m', 'i_rated_A', ...
    'target_torque_A_per_1000', 'actual_current_A_per_1000', ...
    'max_actual_count', 'current_tracking_tol_count', ...
    'traj_amplitude_m', 'traj_frequency_hz', 'traj_cycles', ...
    'position_kp_count_per_m', 'position_kd_count_per_mps', ...
    'protocol2_max_correction_rad'};
verifyFalse(testCase, any(isfield(params, removedParams)));
status = port.readStatus();
verifyEqual(testCase, sort(fieldnames(status)), ...
    sort({'done'; 'fault'; 'fault_id'}));
end

function testAdsSequencerReadsTaskPeriod(testCase)
client = copley.infra.AdsClient(struct('dryRun', true));
client.writeSymbol('GVL_ExperimentSequencer.taskPeriod_s', 0.00025);
port = copley.infra.AdsSequencerPort(client);

verifyEqual(testCase, port.readTaskPeriod_s(), 0.00025);

client.writeSymbol('GVL_ExperimentSequencer.taskPeriod_s', ...
    typecast(0.000125, 'uint8'));
verifyEqual(testCase, port.readTaskPeriod_s(), 0.000125);
end

function testAdsClientRejectsDirectOutputWrites(testCase)
client = copley.infra.AdsClient(struct('dryRun', true));
verifyError(testCase, @()client.writeSymbol('GVL_MotorRuntime.copleyTargetTorque', int16(1)), ...
    'copley:AdsClient:ForbiddenWrite');
verifyError(testCase, @()client.writeSymbol('GVL_MotorRuntime.copleyControlWord', uint16(15)), ...
    'copley:AdsClient:ForbiddenWrite');
verifyError(testCase, @()client.writeSymbol('GVL_MotorRuntime.copleyCommutationAngle', uint16(1)), ...
    'copley:AdsClient:ForbiddenWrite');
verifyError(testCase, @()client.writeSymbol('GVL_MotorRuntime.command', struct()), ...
    'copley:AdsClient:ForbiddenWrite');
verifyError(testCase, @()client.writeSymbol('GVL_MotorRuntime.command.ControlWord', uint16(15)), ...
    'copley:AdsClient:ForbiddenWrite');
verifyError(testCase, @()client.writeSymbol('GVL_MotorRuntime.command.TargetTorque', int16(1)), ...
    'copley:AdsClient:ForbiddenWrite');
verifyError(testCase, @()client.writeSymbol('GVL_ExperimentSequencer.driveCommand.TargetTorque', int16(1)), ...
    'copley:AdsClient:ForbiddenWrite');
verifyError(testCase, @()client.writeSymbol('GVL_MotorRuntime.calibration[1]', struct()), ...
    'copley:AdsClient:ForbiddenWrite');
verifyError(testCase, @()client.writeSymbol( ...
    'GVL_MotorRuntimeInternal.Calibration[1]', struct()), ...
    'copley:AdsClient:ForbiddenWrite');
verifyError(testCase, @()client.writeSymbol( ...
    'GVL_MotorRuntimeInternal.RegisteredReference[1]', struct()), ...
    'copley:AdsClient:ForbiddenWrite');
verifyError(testCase, @()client.writeSymbol( ...
    'GVL_MotorRuntimeInternal.CommissioningReference[1]', struct()), ...
    'copley:AdsClient:ForbiddenWrite');
verifyError(testCase, @()client.writeSymbol( ...
    'GVL_MotorRuntimeInternal.CommutationOverride', struct()), ...
    'copley:AdsClient:ForbiddenWrite');
end

function testProtocol3ResolvesToSingleFixedAngle(testCase)
plan = copley.domain.defaultExperimentPlan();
params = copley.domain.protocolParamsFromPlan(plan, uint16(3));

verifyEqual(testCase, params.angle_count, uint16(1));
verifyEqual(testCase, params.angle_start_rad, 0.0);
verifyEqual(testCase, params.angle_step_rad, 0.0);
end

function testAdsMotorRuntimePortReadsDriverStatus(testCase)
client = copley.infra.AdsClient(struct('dryRun', true));
expected = struct();
expected.StatusWord = uint16(4660);
expected.PositionActualValue = int32(-123);
expected.VelocityActualValue = int32(456);
expected.TorqueActualValue = int16(78);
client.Symbols('GVL_MotorRuntime.Status') = expected;
port = copley.infra.AdsMotorRuntimePort(client);

status = port.readStatus();

verifyEqual(testCase, status.StatusWord, expected.StatusWord);
verifyEqual(testCase, status.PositionActualValue, expected.PositionActualValue);
verifyEqual(testCase, status.VelocityActualValue, expected.VelocityActualValue);
verifyEqual(testCase, status.TorqueActualValue, expected.TorqueActualValue);
end

function testAdsMotorRuntimePortPrefersExplicitFeedbackFault(testCase)
client = copley.infra.AdsClient(struct('dryRun', true));
feedback = struct('encoder_position_raw', int32(-456), ...
    'encoder_velocity_raw', int32(12), ...
    'copley_statusword', uint16(0), ...
    'copley_actual_current_count', int16(34), ...
    'fault_id', uint32(612));
client.Symbols('GVL_MotorRuntimeInternal.Feedback') = feedback;
client.Symbols('GVL_MotorRuntime.Status') = struct( ...
    'StatusWord', uint16(hex2dec('0008')));
port = copley.infra.AdsMotorRuntimePort(client);

status = port.readStatus();

verifyEqual(testCase, status.encoder_position_raw, int32(-456));
verifyTrue(testCase, status.fault);
verifyEqual(testCase, status.fault_id, uint32(612));
end

function testAdsMotorRuntimePortRegistersWholeReferenceByAxis(testCase)
client = copley.infra.AdsClient(struct('dryRun', true));
port = copley.infra.AdsMotorRuntimePort(client);
calibration = copley.domain.makeCalibrationRecord( ...
    localPlanWithElectricalAngleSign(-1), ...
    {struct('theta_offset_hat_rad', 0.25)}, 1.0);
calibration.axis_index = uint16(2);

port.registerReference(calibration);

symbol = 'GVL_MotorRuntimeInternal.RegisteredReference[2]';
validSymbol = 'GVL_MotorRuntimeInternal.RegisteredReferenceValid[2]';
verifyTrue(testCase, isKey(client.Symbols, symbol));
verifyTrue(testCase, client.readSymbol(validSymbol));
stored = client.readSymbol(symbol);
verifyEqual(testCase, fieldnames(stored), { ...
    'reference_position_count'; 'reference_commutation_angle'; ...
    'electrical_direction'});
verifyEqual(testCase, stored.reference_position_count, int32(0));
verifyEqual(testCase, stored.reference_commutation_angle, ...
    copley.domain.radToCopleyUint(0.25 + pi/2));
verifyEqual(testCase, stored.electrical_direction, int16(-1));
verifyFalse(testCase, isfield(stored, 'axis_index'));
verifyFalse(testCase, isfield(stored, 'accepted'));
end

function testCalibrationAndRuntimePortsAcceptAxisFour(testCase)
reference = struct('axis_index', uint16(4), ...
    'reference_position_count', int32(44), ...
    'reference_commutation_angle', uint16(444), ...
    'electrical_direction', int16(1));
calibration = copley.domain.normalizeCalibrationRecord(reference);
[~, canonical] = ...
    copley.domain.toMotorRuntimeCalibrationPayload(calibration);

motor = copley.testing.FakeMotorRuntimePort();
motor.stageReference(canonical);
motor.registerReference(canonical);
verifyEqual(testCase, motor.StagedReference{4}.axis_index, uint16(4));
verifyEqual(testCase, motor.RegisteredReference{4}.axis_index, uint16(4));

client = copley.infra.AdsClient(struct('dryRun', true));
port = copley.infra.AdsMotorRuntimePort(client);
port.registerReference(canonical);
verifyTrue(testCase, isKey(client.Symbols, ...
    'GVL_MotorRuntimeInternal.RegisteredReference[4]'));
verifyTrue(testCase, client.readSymbol( ...
    'GVL_MotorRuntimeInternal.RegisteredReferenceValid[4]'));

for axisIndex = uint16([0 5])
    invalid = reference;
    invalid.axis_index = axisIndex;
    verifyError(testCase, ...
        @()copley.domain.normalizeCalibrationRecord(invalid), ...
        'copley:normalizeCalibrationRecord:InvalidInteger');
    verifyError(testCase, ...
        @()copley.domain.toMotorRuntimeCalibrationPayload(invalid), ...
        'copley:MotorRuntimeReference:InvalidInteger');
end
end

function testCalibrationReferenceUsesOneMeasuredPair(testCase)
plan = copley.domain.defaultExperimentPlan(uint32(56));
plan.position_raw_zero = int32(123456789);
plan.position_zero_m = -0.004;
plan.x_ref_m = 0.123;
plan.tau_e_m = 0.007;
measuredCount = int32(-7654321);
measuredDAxisAngle_rad = 5.75;
result = struct('theta_offset_hat_rad', 0.4, ...
    'estimation_absolute_position_raw', measuredCount, ...
    'theta_at_estimation_rad', measuredDAxisAngle_rad, ...
    'recommended_q_axis_sign', int16(-1));

calibration = copley.domain.makeCalibrationRecord( ...
    plan, {result}, 123.5);
[payload, canonical] = ...
    copley.domain.toMotorRuntimeCalibrationPayload(calibration);

verifyEqual(testCase, calibration.reference_position_count, measuredCount);
verifyEqual(testCase, calibration.reference_commutation_angle, ...
    copley.domain.radToCopleyUint(measuredDAxisAngle_rad - pi/2));
verifyEqual(testCase, calibration.metadata.reference_d_axis_angle_rad, ...
    copley.analysis.wrapTo2Pi(measuredDAxisAngle_rad), 'AbsTol', 1.0e-12);
verifyEqual(testCase, calibration.metadata.accepted_timestamp_s, 123.5);
verifyEqual(testCase, canonical.reference_position_count, ...
    calibration.reference_position_count);
verifyEqual(testCase, canonical.reference_commutation_angle, ...
    calibration.reference_commutation_angle);
verifyEqual(testCase, canonical.metadata.version, uint16(2));
verifyEqual(testCase, fieldnames(payload), { ...
    'reference_position_count'; 'reference_commutation_angle'; ...
    'electrical_direction'});
verifyFalse(testCase, isfield(payload, 'accepted_timestamp_s'));
end

function testRealRegistrationUsesOneWholeRecordWrite(testCase)
client = copley.testing.RecordingAdsClient(false);
port = copley.infra.AdsMotorRuntimePort(client);
calibration = copley.domain.makeCalibrationRecord( ...
    localPlanWithElectricalAngleSign(-1), ...
    {struct('theta_offset_hat_rad', 0.25)}, 1.0);

port.registerReference(calibration);

base = 'GVL_MotorRuntimeInternal.RegisteredReference[1]';
valid = 'GVL_MotorRuntimeInternal.RegisteredReferenceValid[1]';
verifyEqual(testCase, {client.Writes.symbol}, {valid, base, valid});
verifyFalse(testCase, client.Writes(1).value);
verifyEqual(testCase, fieldnames(client.Writes(2).value), { ...
    'reference_position_count'; 'reference_commutation_angle'; ...
    'electrical_direction'});
verifyTrue(testCase, client.Writes(3).value);
end

function testStageAndRegisterUseSeparateStorage(testCase)
client = copley.infra.AdsClient(struct('dryRun', true));
port = copley.infra.AdsMotorRuntimePort(client);
reference = struct('axis_index', uint16(2), ...
    'reference_position_count', int32(11), ...
    'reference_commutation_angle', uint16(22), ...
    'electrical_direction', int16(33));

port.stageReference(reference);

verifyTrue(testCase, isKey(client.Symbols, ...
    'GVL_MotorRuntimeInternal.CommissioningReference[2]'));
verifyFalse(testCase, isKey(client.Symbols, ...
    'GVL_MotorRuntimeInternal.RegisteredReference[2]'));
verifyFalse(testCase, isKey(client.Symbols, ...
    'GVL_MotorRuntimeInternal.RegisteredReferenceValid[2]'));
end

function testRegistrationRequiresAllCommandsIdle(testCase)
client = copley.testing.RecordingAdsClient(false);
client.Symbols('GVL_MotorRuntime.Command.TargetTorque') = int16(1);
port = copley.infra.AdsMotorRuntimePort(client);
reference = struct('axis_index', uint16(1), ...
    'reference_position_count', int32(0), ...
    'reference_commutation_angle', uint16(0), ...
    'electrical_direction', int16(0));

verifyError(testCase, @()port.registerReference(reference), ...
    'copley:AdsMotorRuntimePort:RegistrationNotIdle');
verifyEmpty(testCase, client.Writes);
end

function testRegistrationAllowsShutdownButRejectsOperationEnabled(testCase)
reference = struct('axis_index', uint16(1), ...
    'reference_position_count', int32(0), ...
    'reference_commutation_angle', uint16(0), ...
    'electrical_direction', int16(1));

client = copley.testing.RecordingAdsClient(false);
client.Symbols('GVL_MotorRuntime.Command.ControlWord') = uint16(6);
port = copley.infra.AdsMotorRuntimePort(client);
port.registerReference(reference);
verifyEqual(testCase, numel(client.Writes), 3);

for controlWord = uint16([hex2dec('000F'), hex2dec('001F'), hex2dec('008F')])
    client = copley.testing.RecordingAdsClient(false);
    client.Symbols('GVL_MotorRuntime.Command.ControlWord') = controlWord;
    port = copley.infra.AdsMotorRuntimePort(client);
    verifyError(testCase, @()port.registerReference(reference), ...
        'copley:AdsMotorRuntimePort:RegistrationNotIdle');
    verifyEmpty(testCase, client.Writes);
end
end

function testEl5042RegistrationManifestWritesAllFourAxes(testCase)
client = copley.testing.RecordingAdsClient(false);
port = copley.infra.AdsMotorRuntimePort(client);

result = register_magnetic_pole_references( ...
    'MotorPort', port, 'DryRun', false, 'AllowRetainWrite', true, ...
    'Verbose', false);

verifyFalse(testCase, result.dry_run);
verifyEqual(testCase, numel(result.registered), 4);
verifyEqual(testCase, client.readSymbol( ...
    'GVL_MotorRuntimeInternal.RegisteredReference[1]'), struct( ...
    'reference_position_count', int32(54984708), ...
    'reference_commutation_angle', uint16(49480), ...
    'electrical_direction', int16(1)));
verifyEqual(testCase, client.readSymbol( ...
    'GVL_MotorRuntimeInternal.RegisteredReference[2]'), struct( ...
    'reference_position_count', int32(58408617), ...
    'reference_commutation_angle', uint16(17933), ...
    'electrical_direction', int16(1)));
verifyEqual(testCase, client.readSymbol( ...
    'GVL_MotorRuntimeInternal.RegisteredReference[3]'), struct( ...
    'reference_position_count', int32(61902867), ...
    'reference_commutation_angle', uint16(63448), ...
    'electrical_direction', int16(1)));
verifyEqual(testCase, client.readSymbol( ...
    'GVL_MotorRuntimeInternal.RegisteredReference[4]'), struct( ...
    'reference_position_count', int32(65824016), ...
    'reference_commutation_angle', uint16(57717), ...
    'electrical_direction', int16(1)));
verifyTrue(testCase, client.readSymbol( ...
    'GVL_MotorRuntimeInternal.RegisteredReferenceValid[1]'));
verifyTrue(testCase, client.readSymbol( ...
    'GVL_MotorRuntimeInternal.RegisteredReferenceValid[2]'));
verifyTrue(testCase, client.readSymbol( ...
    'GVL_MotorRuntimeInternal.RegisteredReferenceValid[3]'));
verifyTrue(testCase, client.readSymbol( ...
    'GVL_MotorRuntimeInternal.RegisteredReferenceValid[4]'));
verifyEqual(testCase, {client.Writes.symbol}, { ...
    'GVL_MotorRuntimeInternal.RegisteredReferenceValid[1]', ...
    'GVL_MotorRuntimeInternal.RegisteredReferenceValid[2]', ...
    'GVL_MotorRuntimeInternal.RegisteredReferenceValid[3]', ...
    'GVL_MotorRuntimeInternal.RegisteredReferenceValid[4]', ...
    'GVL_MotorRuntimeInternal.RegisteredReference[1]', ...
    'GVL_MotorRuntimeInternal.RegisteredReference[2]', ...
    'GVL_MotorRuntimeInternal.RegisteredReference[3]', ...
    'GVL_MotorRuntimeInternal.RegisteredReference[4]', ...
    'GVL_MotorRuntimeInternal.RegisteredReferenceValid[1]', ...
    'GVL_MotorRuntimeInternal.RegisteredReferenceValid[2]', ...
    'GVL_MotorRuntimeInternal.RegisteredReferenceValid[3]', ...
    'GVL_MotorRuntimeInternal.RegisteredReferenceValid[4]'});
end

function testFourAxisRegistrationManifestDryRun(testCase)
manifestFile = localWriteMagneticPoleManifest([4 2 1 3]);
fileCleanup = onCleanup(@()delete(manifestFile));
motor = copley.testing.FakeMotorRuntimePort();

result = register_magnetic_pole_references( ...
    'ManifestFile', manifestFile, 'MotorPort', motor, ...
    'DryRun', true, 'Verbose', false);

verifyTrue(testCase, result.dry_run);
verifyEqual(testCase, numel(result.registered), 4);
verifyEqual(testCase, motor.RegisterCount, 4);
for axisIndex = 1:4
    verifyEqual(testCase, ...
        result.registered{axisIndex}.axis_index, uint16(axisIndex));
    verifyEqual(testCase, ...
        motor.RegisteredReference{axisIndex}.axis_index, uint16(axisIndex));
end
clear fileCleanup
end

function testRegistrationManifestRejectsIncompleteAxisSets(testCase)
localVerifyManifestError(testCase, [1 2 3], ...
    'register_magnetic_pole_references:InvalidAxes');
localVerifyManifestError(testCase, [1 1], ...
    'register_magnetic_pole_references:DuplicateAxis');
localVerifyManifestError(testCase, [1 3], ...
    'register_magnetic_pole_references:MissingAxis');
localVerifyManifestError(testCase, [0 2], ...
    'copley:MotorRuntimeReference:InvalidInteger');
localVerifyManifestError(testCase, [1 5], ...
    'copley:MotorRuntimeReference:InvalidInteger');
end

function testIndependentReferenceFormulaProducesDifferentAxisAngles(testCase)
currentPosition = -55717450;
referencePosition = [-57895945, -55717425];
referenceAngle = [22751, 18746];
direction = [-1, -1];
actual = mod(round(referenceAngle + direction .* ...
    (currentPosition - referencePosition) * 65536 / 360000), 65536);

verifyEqual(testCase, actual, [19384, 18751]);
verifyNotEqual(testCase, actual(1), actual(2));
end

function testRadToCopleyUintWrapsCardinalAngles(testCase)
angles = [0, pi/2, pi, 3*pi/2, 2*pi, -pi/2];
expected = uint16([0, 16384, 32768, 49152, 0, 49152]);

actual = arrayfun(@copley.domain.radToCopleyUint, angles);

verifyEqual(testCase, actual, expected);
end

function testEstimationReferenceKeepsRawCountAndAngleAtSameRow(testCase)
samples = table(int32([100; 200; 300]), [0.0; 0.01; 0.02], ...
    'VariableNames', {'encoder_position_raw', 'x_abs_m'});
plan = copley.domain.defaultExperimentPlan();
plan.x_ref_m = 0.005;
plan.tau_e_m = 0.04;
thetaOffset_rad = 0.3;

estimate = copley.analysis.buildEstimationReference( ...
    samples, plan, thetaOffset_rad);
expectedAngle_rad = copley.analysis.wrapTo2Pi( ...
    thetaOffset_rad + 2*pi*(0.01 - plan.x_ref_m)/plan.tau_e_m);

verifyEqual(testCase, estimate.estimation_absolute_position_raw, int32(200));
verifyEqual(testCase, estimate.estimation_position_m, 0.01, ...
    'AbsTol', 1.0e-15);
verifyEqual(testCase, estimate.theta_at_estimation_rad, ...
    expectedAngle_rad, 'AbsTol', 1.0e-12);
end

function testMotorReferencePackingUsesFixedEightByteAbi(testCase)
payload = struct('reference_position_count', int32(-123456789), ...
    'reference_commutation_angle', uint16(hex2dec('BEEF')), ...
    'electrical_direction', int16(-123));

bytes = copley.infra.packMotorCalibration(payload);
expected = [typecast(int32(-123456789), 'uint8'), ...
    typecast(uint16(hex2dec('BEEF')), 'uint8'), ...
    typecast(int16(-123), 'uint8')];

verifyEqual(testCase, bytes, expected);
verifyEqual(testCase, numel(bytes), 8);
end

function testLegacyCalibrationRecordConvertsToVersionTwoReference(testCase)
legacy = struct('axis_index', uint16(2), 'version', uint16(1), ...
    'valid', true, 'accepted', true, 'accepted_timestamp_s', 42.0, ...
    'theta_offset_rad', 0.25, 'q_axis_sign', int16(-1), ...
    'electrical_angle_sign', int16(-1), ...
    'position_raw_zero', int32(-123), 'position_zero_m', 0.002, ...
    'x_ref_m', 0.001, 'tau_e_m', 0.04);
expectedDAxis = copley.analysis.wrapTo2Pi(0.25 - 2*pi*0.001/0.04);

calibration = copley.domain.normalizeCalibrationRecord(legacy);

verifyEqual(testCase, calibration.axis_index, uint16(2));
verifyEqual(testCase, calibration.reference_position_count, int32(-123));
verifyEqual(testCase, calibration.reference_commutation_angle, ...
    copley.domain.radToCopleyUint(expectedDAxis - pi/2));
verifyEqual(testCase, calibration.metadata.version, uint16(2));
verifyEqual(testCase, calibration.metadata.source_version, uint16(1));
verifyTrue(testCase, calibration.metadata.valid);
verifyTrue(testCase, calibration.metadata.accepted);
verifyEqual(testCase, calibration.metadata.accepted_timestamp_s, 42.0);
renormalized = copley.domain.normalizeCalibrationRecord(calibration);
verifyEqual(testCase, renormalized.metadata.source_version, uint16(1));
end

function testMotorRuntimeRegistersArbitraryDirectionAndIgnoresMetadataVersion(testCase)
motor = copley.testing.FakeMotorRuntimePort();
reference = struct('axis_index', uint16(1), ...
    'reference_position_count', int32(0), ...
    'reference_commutation_angle', uint16(0), ...
    'electrical_direction', int16(7), ...
    'metadata', struct('version', uint16(1), ...
        'valid', false, 'accepted', false));

motor.registerReference(reference);

verifyEqual(testCase, motor.RegisterCount, 1);
verifyEqual(testCase, ...
    motor.RegisteredReference{1}.electrical_direction, int16(7));
verifyEqual(testCase, ...
    motor.RegisteredReference{1}.metadata.version, uint16(1));
end

function testVirtualCstAdsWriterSurfaceIsAbsent(testCase)
repoRoot = fileparts(testCase.TestData.MatlabDir);
removedFiles = { ...
    fullfile(testCase.TestData.MatlabDir, '+copley', '+infra', ...
        'AdsVirtualCstPort.m'), ...
    fullfile(testCase.TestData.MatlabDir, '+copley', '+ports', ...
        'VirtualCstPort.m'), ...
    fullfile(testCase.TestData.MatlabDir, 'run_virtual_cst_main.m'), ...
    fullfile(repoRoot, 'config', 'copley', 'virtual_cst.example.json')};
for i = 1:numel(removedFiles)
    verifyFalse(testCase, exist(removedFiles{i}, 'file') == 2);
end

clientMethods = methods(copley.infra.AdsClient(struct('dryRun', true)));
verifyFalse(testCase, any(strcmp(clientMethods, 'writeVirtualCstRequest')));
verifyFalse(testCase, any(strcmp(clientMethods, ...
    'writeVirtualCstAuthorization')));
end

function testVirtualCstBoundaryIsProducerIndependentAndRatedScaled(testCase)
repoRoot = fileparts(testCase.TestData.MatlabDir);
projectText = fileread(fullfile(repoRoot, 'twincat', 'NikonMotorProject2025.tsproj'));
publicGvlText = fileread(fullfile(repoRoot, 'twincat', 'MotorRuntime', 'GVLs', ...
    'GVL_MotorRuntime.TcGVL'));
internalGvlText = fileread(fullfile(repoRoot, 'twincat', 'MotorRuntime', 'GVLs', ...
    'GVL_MotorRuntimeInternal.TcGVL'));
commandText = fileread(fullfile(repoRoot, 'twincat', 'MotorRuntime', 'DUTs', ...
    'DUT_MotorDriverCommand.TcDUT'));
statusText = fileread(fullfile(repoRoot, 'twincat', 'MotorRuntime', 'DUTs', ...
    'DUT_MotorDriverStatus.TcDUT'));
arbiterText = fileread(fullfile(repoRoot, 'twincat', 'MotorRuntime', 'POUs', ...
    'FB_MotorCommandArbiter.TcPOU'));
kernelText = fileread(fullfile(repoRoot, 'twincat', 'MotorRuntime', 'POUs', ...
    'FB_MotorRuntimeKernel.TcPOU'));
mappingsText = regexp(projectText, '<Mappings>[\s\S]*?</Mappings>', ...
    'match', 'once');

verifyNotEmpty(testCase, regexp(publicGvlText, ...
    ['VAR_GLOBAL\s*' ...
     '//[^\n]*\s*Command\s+AT\s+%I\*\s*:\s*DUT_MotorDriverCommand;\s*' ...
     'Status\s+AT\s+%Q\*\s*:\s*DUT_MotorDriverStatus;\s*END_VAR'], ...
    'once'));
verifyNotEmpty(testCase, regexp(commandText, ...
    ['TYPE DUT_MotorDriverCommand : STRUCT\s*' ...
     'ControlWord\s*:\s*WORD;\s*TargetTorque\s*:\s*INT;\s*' ...
     'END_STRUCT'], 'once'));
verifyNotEmpty(testCase, regexp(statusText, ...
    ['TYPE DUT_MotorDriverStatus : STRUCT\s*' ...
     'StatusWord\s*:\s*WORD;\s*PositionActualValue\s*:\s*DINT;\s*' ...
     'VelocityActualValue\s*:\s*DINT;\s*TorqueActualValue\s*:\s*INT;\s*' ...
     'END_STRUCT'], 'once'));
verifyEmpty(testCase, strfind(internalGvlText, 'CommandGuard'));
verifyEmpty(testCase, strfind(internalGvlText, 'NormalAuthorization'));
verifyNotEmpty(testCase, strfind(arbiterText, ...
    'SelectedCommand.ControlWord := NormalCommand.ControlWord;'));
verifyNotEmpty(testCase, strfind(arbiterText, ...
    'SelectedCommand.TargetTorque := NormalCommand.TargetTorque;'));
verifyNotEmpty(testCase, regexp(internalGvlText, ...
    ['VIRTUAL_RATED_TORQUE_EQUIVALENT_CURRENT_MA\s*:\s*DINT\s*' ...
     ':=\s*2000;'], 'once'));
verifyNotEmpty(testCase, regexp(internalGvlText, ...
    ['COPLEY_INTERNAL_CURRENT_MA_PER_1000_COUNT\s*:\s*DINT\s*' ...
     ':=\s*100;'], 'once'));
verifyNotEmpty(testCase, regexp(kernelText, ...
    ['IF NOT overrideRequired THEN\s*scaledTorqueDint\s*:=\s*' ...
     'INT_TO_DINT\(Command\.TargetTorque\)[\s\S]*?' ...
     'VIRTUAL_RATED_TORQUE_EQUIVALENT_CURRENT_MA[\s\S]*?' ...
     'COPLEY_INTERNAL_CURRENT_MA_PER_1000_COUNT;'], 'once'));
verifyEmpty(testCase, strfind(kernelText, 'limitFlags'));
verifyNotEmpty(testCase, regexp(kernelText, ...
    ['statusActualNumerator\s*:=\s*statusActualDint[\s\S]*?' ...
     'COPLEY_INTERNAL_CURRENT_MA_PER_1000_COUNT;[\s\S]*?' ...
     'statusActualDenominator\s*:=[\s\S]*?' ...
     'VIRTUAL_RATED_TORQUE_EQUIVALENT_CURRENT_MA;'], 'once'));
verifyNotEmpty(testCase, regexp(projectText, ...
    ['linear_exp_2025a_P\.CURRENT_TO_UNIT</Name>\s*' ...
     '<Value>500</Value>'], 'once'));
verifyNotEmpty(testCase, regexp(projectText, ...
    ['linear_exp_2025a_P\.MAX_INPUT</Name>\s*' ...
     '<Value>2\.8</Value>'], 'once'));

virtualCommands = [-1639, -1638, -1400, -1000, 0, 1000, 1400, 1638, 1639];
physicalCounts = min(max(virtualCommands * 20, -32768), 32767);
verifyEqual(testCase, physicalCounts, ...
    [-32768, -32760, -28000, -20000, 0, 20000, 28000, 32760, 32767]);
physicalFeedbackSums = [40000, 20000, 0, -20000, -40000];
virtualFeedback = sign(physicalFeedbackSums) .* ...
    floor(abs(physicalFeedbackSums) / 40 + 0.5);
verifyEqual(testCase, virtualFeedback, [1000, 500, 0, -500, -1000]);
verifyNotEmpty(testCase, regexp(arbiterText, ...
    ['commissioningRequested\s*:=\s*' ...
     'CommutationOverride.enable AND normalCommandZero;'], 'once'));
verifyEmpty(testCase, strfind(arbiterText, 'controlWordAllowed'));
verifyEmpty(testCase, strfind(arbiterText, 'torqueAllowed'));
verifyEmpty(testCase, strfind(arbiterText, 'safeZeroCycleDone'));
verifyEmpty(testCase, strfind(arbiterText, 'resetPulseRemaining'));

verifyNotEmpty(testCase, mappingsText);
requiredMappingFragments = { ...
    'copleyActualCurrentCountModule1" VarB="Module 1'; ...
    'copleyStatusWordModule1" VarB="Module 1'; ...
    'copleyCommutationAngleModule1" VarB="Module 1'; ...
    'copleyControlWordModule1" VarB="Module 1'; ...
    'copleyTargetTorqueModule1" VarB="Module 1'; ...
    'copleyActualCurrentCountModule2" VarB="Module 2'; ...
    'copleyStatusWordModule2" VarB="Module 2'; ...
    'copleyCommutationAngleModule2" VarB="Module 2'; ...
    'copleyControlWordModule2" VarB="Module 2'; ...
    'copleyTargetTorqueModule2" VarB="Module 2'; ...
    'GVL_MotorRuntime.Command^ControlWord" VarB="motor_config_Y^controlWord'; ...
    'GVL_MotorRuntime.Command^TargetTorque" VarB="TcModuleOutput^LinearSystem^TargetTorque'; ...
    'GVL_MotorRuntime.Status^StatusWord" VarB="motor_config_U^statusWord'; ...
    'GVL_MotorRuntime.Status^PositionActualValue" VarB="TcModuleInput^LinearSystem^Positionactualvalue'; ...
    'GVL_MotorRuntime.Status^VelocityActualValue" VarB="TcModuleInput^LinearSystem^Velocityactualvalue'; ...
    'GVL_MotorRuntime.Status^TorqueActualValue" VarB="TcModuleInput^LinearSystem^Torqueactualvalue1'};
for i = 1:numel(requiredMappingFragments)
    verifyNotEmpty(testCase, strfind(mappingsText, requiredMappingFragments{i}));
end
verifyEmpty(testCase, regexp(mappingsText, ...
    ['PRG_MotorRuntime\.copley(StatusWord|ActualCurrentCount|' ...
     'ControlWord|TargetTorque|CommutationAngle)\[[12]\]'], 'once'));

verifyNotEmpty(testCase, strfind(arbiterText, ...
    'CommissioningActive         : BOOL;'));
end

function testVirtualCstCompileTimeAxisModeScopesNormalPath(testCase)
repoRoot = fileparts(testCase.TestData.MatlabDir);
internalGvlText = fileread(fullfile(repoRoot, 'twincat', 'MotorRuntime', 'GVLs', ...
    'GVL_MotorRuntimeInternal.TcGVL'));
kernelText = fileread(fullfile(repoRoot, 'twincat', 'MotorRuntime', 'POUs', ...
    'FB_MotorRuntimeKernel.TcPOU'));
programText = fileread(fullfile(repoRoot, 'twincat', 'MotorRuntime', 'POUs', ...
    'PRG_MotorRuntime.TcPOU'));

verifyNotEmpty(testCase, regexp(internalGvlText, ...
    'AXIS_COUNT\s*:\s*UINT\s*:=\s*4;', 'once'));
verifyNotEmpty(testCase, regexp(internalGvlText, ...
    'NORMAL_FOUR_AXIS_ENABLED\s*:\s*BOOL\s*:=\s*TRUE;', 'once'));
verifyNotEmpty(testCase, regexp(internalGvlText, ...
    ['TORQUE_LINKAGE_LOWER_COUNT\s*:\s*ARRAY\s*' ...
     '\[1\.\.AXIS_COUNT\]\s*OF\s*DINT\s*:=\s*\[\s*' ...
     '54054804,\s*55809159,\s*59369714,\s*63068811\s*\];'], ...
    'once'));
verifyNotEmpty(testCase, regexp(internalGvlText, ...
    ['TORQUE_LINKAGE_UPPER_COUNT\s*:\s*ARRAY\s*' ...
     '\[1\.\.AXIS_COUNT\]\s*OF\s*DINT\s*:=\s*\[\s*' ...
     '57600015,\s*61230980,\s*64809681,\s*66655810\s*\];'], ...
    'once'));
verifyNotEmpty(testCase, regexp(kernelText, ...
    ['normalAxisActive\[i\]\s*:=\s*\(i <= 2\)\s*' ...
     'OR GVL_MotorRuntimeInternal\.NORMAL_FOUR_AXIS_ENABLED;'], ...
    'once'));
verifyNotEmpty(testCase, regexp(kernelText, ...
    ['torqueAxisLinked\[i\]\s*:=\s*normalAxisActive\[i\]\s*' ...
     'AND \(EncoderPositionActualRaw >= GVL_MotorRuntimeInternal\.' ...
     'TORQUE_LINKAGE_LOWER_COUNT\[i\]\s*-\s*' ...
     'GVL_MotorRuntimeInternal\.TORQUE_LINKAGE_MARGIN_COUNT\)\s*' ...
     'AND \(EncoderPositionActualRaw <= GVL_MotorRuntimeInternal\.' ...
     'TORQUE_LINKAGE_UPPER_COUNT\[i\]\s*\+\s*' ...
     'GVL_MotorRuntimeInternal\.TORQUE_LINKAGE_MARGIN_COUNT\);'], 'once'));
verifyNotEmpty(testCase, regexp(internalGvlText, ...
    'TORQUE_LINKAGE_MARGIN_COUNT\s*:\s*DINT\s*:=\s*186127;', 'once'));
verifyNotEmpty(testCase, regexp(kernelText, ...
    ['IF normalAxisActive\[i\] THEN\s*' ...
     'activeAxisCount := activeAxisCount \+ 1;\s*' ...
     'registeredReferencesValid :=\s*' ...
     'registeredReferencesValid AND RegisteredReferenceValid\[i\];'], ...
    'once'));
verifyNotEmpty(testCase, regexp(kernelText, ...
    ['IF normalAxisActive\[i\] THEN\s*' ...
     'copleyFault := copleyFault OR copleyFaultByAxis\[i\];'], ...
    'once'));
verifyNotEmpty(testCase, strfind(kernelText, ...
    'ELSIF NOT overrideRequired AND Ready AND normalAxisActive[i] THEN'));
verifyNotEmpty(testCase, regexp(kernelText, ...
    ['IF normalAxisActive\[i\] THEN\s*' ...
     'CopleyControlWord\[i\] := limitedCommand\.ControlWord;\s*' ...
     'IF torqueAxisLinked\[i\] THEN\s*' ...
     'CopleyTargetTorque\[i\] := limitedCommand\.TargetTorque;\s*' ...
     'END_IF'], ...
    'once'));
verifyNotEmpty(testCase, regexp(kernelText, ...
    ['IF normalAxisActive\[i\] THEN\s*statusActualDint :=\s*' ...
     'statusActualDint \+ INT_TO_DINT\(CopleyActualCurrentCount\[i\]\);'], ...
    'once'));
verifyNotEmpty(testCase, regexp(kernelText, ...
    ['statusActualDenominator\s*:=\s*activeAxisCount\s*\*\s*' ...
     'GVL_MotorRuntimeInternal\.' ...
     'VIRTUAL_RATED_TORQUE_EQUIVALENT_CURRENT_MA;'], 'once'));
verifyNotEmpty(testCase, regexp(kernelText, ...
    ['IF overrideRequired THEN\s*IF Ready THEN\s*' ...
     'CopleyControlWord\[axisIndexInt\] := limitedCommand\.ControlWord;\s*' ...
     'CopleyTargetTorque\[axisIndexInt\] := limitedCommand\.TargetTorque;'], ...
    'once'));

requiredProgramFragments = { ...
    'copleyStatusWord[3] := copleyStatusWordModule3;'; ...
    'copleyStatusWord[4] := copleyStatusWordModule4;'; ...
    'copleyTargetTorqueModule3 := fbMotor.CopleyTargetTorque[3];'; ...
    'copleyTargetTorqueModule4 := fbMotor.CopleyTargetTorque[4];'; ...
    'copleyTargetTorqueModule3 := 0;'; ...
    'copleyTargetTorqueModule4 := 0;'};
for i = 1:numel(requiredProgramFragments)
    verifyNotEmpty(testCase, strfind(programText, requiredProgramFragments{i}));
end

fourAxisEnabled = [false, true];
expectedOutputs = {[0, 0, 0, 0], [0, 0, 20000, 20000]};
expectedReferenceValid = [true, false];
expectedFault = [false, true];
expectedTorqueActual = [1250, 1750];
expectedMinimumStateRank = [3, 0];
referenceValid = [true, true, false, false];
axisFault = [false, false, true, false];
axisStateRank = [4, 3, 1, 0];
actualCurrent = [20000, 30000, 40000, 50000];
linkedAxes = [false, false, true, true];
for i = 1:numel(fourAxisEnabled)
    activeAxes = [true, true, fourAxisEnabled(i), fourAxisEnabled(i)];
    outputs = zeros(1, 4);
    outputs(activeAxes & linkedAxes) = 20000;
    verifyEqual(testCase, outputs, expectedOutputs{i});
    verifyEqual(testCase, all(referenceValid(activeAxes)), ...
        expectedReferenceValid(i));
    verifyEqual(testCase, any(axisFault(activeAxes)), ...
        expectedFault(i));
    verifyEqual(testCase, min(axisStateRank(activeAxes)), ...
        expectedMinimumStateRank(i));
    torqueActual = sum(actualCurrent(activeAxes)) * 100 ...
        / (sum(activeAxes) * 2000);
    verifyEqual(testCase, torqueActual, expectedTorqueActual(i));
end

positions = int32([ ...
    54054803; 54900000; 56000000; 58500000; 60000000; ...
    62000000; 64000000; 65700000; 66655811]);
lowerCounts = int32([54054804, 55809159, 59369714, 63068811]);
upperCounts = int32([57600015, 61230980, 64809681, 66655810]);
expectedLinkedAxes = logical([ ...
    0, 0, 0, 0; ...
    1, 0, 0, 0; ...
    1, 1, 0, 0; ...
    0, 1, 0, 0; ...
    0, 1, 1, 0; ...
    0, 0, 1, 0; ...
    0, 0, 1, 1; ...
    0, 0, 0, 1; ...
    0, 0, 0, 0]);
actualLinkedAxes = positions >= lowerCounts & positions <= upperCounts;
verifyEqual(testCase, actualLinkedAxes, expectedLinkedAxes);
% At the observed park position below Core1, pre-excitation must be available.
margin = int32(186127);
park = int32(54031509);
verifyEqual(testCase, park >= lowerCounts-margin & park <= upperCounts+margin, ...
    logical([1, 0, 0, 0]));
% Check inclusive extended edges and the immediately adjacent OFF positions.
for axis = 1:4
    lo = lowerCounts(axis)-margin;
    hi = upperCounts(axis)+margin;
    probes = [lo-1, lo, hi, hi+1];
    verifyEqual(testCase, probes >= lo & probes <= hi, logical([0, 1, 1, 0]));
end
end

function testMotorIoWatchdogGuardsPdoAndPublishesFeedbackAbi(testCase)
repoRoot = fileparts(testCase.TestData.MatlabDir);
projectText = fileread(fullfile(repoRoot, 'twincat', 'NikonMotorProject2025.tsproj'));
programText = fileread(fullfile(repoRoot, 'twincat', 'MotorRuntime', 'POUs', ...
    'PRG_MotorRuntime.TcPOU'));
watchdogText = fileread(fullfile(repoRoot, 'twincat', 'MotorRuntime', 'POUs', ...
    'FB_MotorIoWatchdog.TcPOU'));
feedbackText = fileread(fullfile(repoRoot, 'twincat', 'MotorRuntime', 'DUTs', ...
    'DUT_MotorFeedbackSnapshot.TcDUT'));
sequencerFeedbackText = fileread(fullfile(repoRoot, 'twincat', 'ExperimentSequencer', ...
    'DUTs', 'DUT_MotorFeedbackSnapshot.TcDUT'));
motorOverrideText = fileread(fullfile(repoRoot, 'twincat', 'MotorRuntime', 'DUTs', ...
    'DUT_CommutationOverride.TcDUT'));
sequencerOverrideText = fileread(fullfile(repoRoot, 'twincat', 'ExperimentSequencer', ...
    'DUTs', 'DUT_CommutationOverride.TcDUT'));
loggerText = fileread(fullfile(repoRoot, 'twincat', 'ExperimentSequencer', 'POUs', ...
    'FB_ExperimentLogger.TcPOU'));
loggerSampleText = fileread(fullfile(repoRoot, 'twincat', 'ExperimentSequencer', ...
    'DUTs', 'DUT_LoggerSample.TcDUT'));
adsLoggerText = fileread(fullfile(testCase.TestData.MatlabDir, '+copley', ...
    '+infra', 'AdsLoggerPort.m'));

encoderMappingText = localMappingOwnerBlock(projectText, ...
    'TIID^Device 3 (EtherCAT)^Term 1 (EK1100)^Term 2 (EL5042)');
driveMappingText = { ...
    localMappingOwnerBlock(projectText, ...
        'TIID^Device 3 (EtherCAT)^Drive 7 (XE2)'), ...
    localMappingOwnerBlock(projectText, ...
        'TIID^Device 3 (EtherCAT)^Drive 8 (XE2)')};
requiredMappings = { ...
    encoderMappingText, 'encoderPositionRaw" VarB="FB Inputs Channel 1^Position'; ...
    encoderMappingText, 'encoderReady" VarB="FB Inputs Channel 1^Status^Ready'; ...
    encoderMappingText, 'encoderError" VarB="FB Inputs Channel 1^Status^Error'; ...
    encoderMappingText, 'encoderTxPdoState" VarB="FB Inputs Channel 1^Status^TxPDO State'; ...
    encoderMappingText, 'encoderWcState" VarB="WcState^WcState'; ...
    encoderMappingText, 'encoderInputToggle" VarB="WcState^InputToggle'; ...
    driveMappingText{1}, 'copleyWcState" VarB="WcState^WcState'; ...
    driveMappingText{1}, 'copleyInputToggle" VarB="WcState^InputToggle'; ...
    driveMappingText{2}, 'copleyWcStateDrive2" VarB="WcState^WcState'; ...
    driveMappingText{2}, 'copleyInputToggleDrive2" VarB="WcState^InputToggle'};
for i = 1:size(requiredMappings, 1)
    verifyNotEmpty(testCase, ...
        strfind(requiredMappings{i, 1}, requiredMappings{i, 2}));
end
for logicalAxis = 1:4
    physicalModule = mod(logicalAxis - 1, 2) + 1;
    ownerIndex = ceil(logicalAxis / 2);
    fragments = { ...
        sprintf(['copleyActualCurrentCountModule%d" VarB="Module %d ' ...
            '(Cyclic torque with commutation angle Mode)^Cyclic torque ' ...
            'with commutation angle Inputs^Torque actual value'], ...
            logicalAxis, physicalModule), ...
        sprintf(['copleyStatusWordModule%d" VarB="Module %d ' ...
            '(Cyclic torque with commutation angle Mode)^Cyclic torque ' ...
            'with commutation angle Inputs^Status word'], ...
            logicalAxis, physicalModule), ...
        sprintf(['copleyControlWordModule%d" VarB="Module %d ' ...
            '(Cyclic torque with commutation angle Mode)^Cyclic torque ' ...
            'with commutation angle Outputs^Control word'], ...
            logicalAxis, physicalModule), ...
        sprintf(['copleyTargetTorqueModule%d" VarB="Module %d ' ...
            '(Cyclic torque with commutation angle Mode)^Cyclic torque ' ...
            'with commutation angle Outputs^Target Torque'], ...
            logicalAxis, physicalModule), ...
        sprintf(['copleyCommutationAngleModule%d" VarB="Module %d ' ...
            '(Cyclic torque with commutation angle Mode)^Cyclic torque ' ...
            'with commutation angle Outputs^Commutation angle'], ...
            logicalAxis, physicalModule)};
    for fragmentIndex = 1:numel(fragments)
        verifyNotEmpty(testCase, ...
            strfind(driveMappingText{ownerIndex}, fragments{fragmentIndex}));
    end
end
verifyNotEmpty(testCase, strfind(projectText, ...
    '20002300020000001e00417869732041204465736972656420616d706c6966696572207374617465'));

verifyNotEmpty(testCase, strfind(watchdogText, ...
    'FaultId := 620; // Encoder EtherCAT process data invalid'));
verifyNotEmpty(testCase, strfind(watchdogText, ...
    'FaultId := 621; // Encoder valid input telegram stale'));
verifyNotEmpty(testCase, strfind(watchdogText, ...
    'FaultId := 622; // Copley EtherCAT process data invalid'));
verifyNotEmpty(testCase, strfind(watchdogText, ...
    'FaultId := 623; // Copley valid input telegram stale'));
verifyNotEmpty(testCase, strfind(watchdogText, ...
    'ELSIF ResetRequest'));
verifyNotEmpty(testCase, strfind(watchdogText, ...
    'AND CommandIsZero'));
verifyNotEmpty(testCase, strfind(watchdogText, ...
    'EncoderError OR NOT EncoderReady'));
verifyNotEmpty(testCase, strfind(watchdogText, ...
    'EncoderWcState OR EncoderTxPdoState'));
verifyNotEmpty(testCase, strfind(programText, ...
    'Copley2WcState := copleyWcStateDrive2'));
verifyNotEmpty(testCase, strfind(programText, ...
    'Copley2InputToggle := copleyInputToggleDrive2'));
verifyNotEmpty(testCase, strfind(watchdogText, ...
    'CopleyWcState OR Copley2WcState'));
verifyNotEmpty(testCase, strfind(watchdogText, ...
    'Copley2InputStaleCycles'));
verifyNotEmpty(testCase, regexp(watchdogText, ...
    ['SafeToDrive\s*:=\s*[\s\S]*?AND NOT CopleyWcState\s*' ...
     'AND NOT Copley2WcState[\s\S]*?AND copleyToggleHealthy\s*' ...
     'AND copley2ToggleHealthy;'], 'once'));
verifyNotEmpty(testCase, regexp(programText, ...
    ['ResetRequest :=\s*' ...
     'GVL_MotorRuntimeInternal\.IoWatchdogResetRequest\s*' ...
     'AND \(fbArbiter\.CommissioningActive\s*' ...
     'OR NOT fbArbiter\.CommissioningActive\)'], 'once'));
verifyNotEmpty(testCase, strfind(programText, ...
    'GVL_MotorRuntimeInternal.IoWatchdogResetRequest := FALSE;'));
verifyNotEmpty(testCase, regexp(programText, ...
    ['IF \(fbArbiter\.CommissioningActive OR ' ...
     'NOT fbArbiter\.CommissioningActive\)\s*' ...
      'AND fbIoWatchdog\.SafeToDrive THEN[\s\S]*?ELSE[\s\S]*?' ...
      'copleyControlWordModule1 := WORD#16#0000;\s*' ...
      'copleyTargetTorqueModule1 := 0;[\s\S]*?' ...
      'copleyControlWordModule2 := WORD#16#0000;\s*' ...
      'copleyTargetTorqueModule2 := 0;[\s\S]*?' ...
      'copleyControlWordModule3 := WORD#16#0000;\s*' ...
      'copleyTargetTorqueModule3 := 0;[\s\S]*?' ...
      'copleyControlWordModule4 := WORD#16#0000;\s*' ...
      'copleyTargetTorqueModule4 := 0;'], 'once'));
verifyEmpty(testCase, strfind(feedbackText, 'encoder_wcstate'));
feedbackFields = regexp(feedbackText, ...
    '(?m)^\s+([A-Za-z]\w*)\s*:\s*[A-Za-z]\w*;', 'tokens');
feedbackFields = cellfun(@(x)x{1}, feedbackFields, 'UniformOutput', false);
verifyEqual(testCase, feedbackFields, {'encoder_position_raw', ...
    'encoder_velocity_raw', 'copley_statusword', ...
    'copley_actual_current_count', 'output_torque_count', 'fault_id'});
sequencerFeedbackFields = regexp(sequencerFeedbackText, ...
    '(?m)^\s+([A-Za-z]\w*)\s*:\s*[A-Za-z]\w*;', 'tokens');
sequencerFeedbackFields = cellfun(@(x)x{1}, sequencerFeedbackFields, ...
    'UniformOutput', false);
verifyEqual(testCase, feedbackFields, sequencerFeedbackFields);
verifyEmpty(testCase, strfind(motorOverrideText, 'producer_cycle_counter'));
verifyEmpty(testCase, strfind(sequencerOverrideText, 'producer_cycle_counter'));
verifyEmpty(testCase, strfind(loggerSampleText, 'encoder_wcstate'));
verifyEmpty(testCase, strfind(loggerText, 'sample.encoder_wcstate'));
verifyNotEmpty(testCase, regexp(adsLoggerText, ...
    'function bytes = localLoggerSampleBytes\(\)\s*bytes = 72;', ...
    'once'));
removedLoggerFields = {'lease_id', 'state', 'producer_cycle_counter', ...
    'copley_statusword', 'comm_angle_u16', 'limit_flags', ...
    'iq_cmd_count_req', 'target_current_count'};
for i = 1:numel(removedLoggerFields)
    verifyEmpty(testCase, regexp(loggerSampleText, ...
        ['\<' removedLoggerFields{i} '\>\s*:'], 'once'));
end
end

function testQAxisUsesDifferentialSweepWithNegativeSecondPulse(testCase)
repoRoot = fileparts(testCase.TestData.MatlabDir);
diffText = fileread(fullfile(repoRoot, 'twincat', 'ExperimentSequencer', 'POUs', ...
    'FB_DifferentialSweep.TcPOU'));
sequencerText = fileread(fullfile(repoRoot, 'twincat', 'ExperimentSequencer', 'POUs', ...
    'FB_ExperimentSequencer.TcPOU'));
projectText = fileread(fullfile(repoRoot, 'twincat', 'ExperimentSequencer', ...
    'ExperimentSequencer.plcproj'));

verifyFalse(testCase, exist(fullfile(repoRoot, 'twincat', 'ExperimentSequencer', ...
    'POUs', 'FB_QAxisVerification.TcPOU'), 'file') == 2);
verifyEmpty(testCase, strfind(projectText, 'FB_QAxisVerification.TcPOU'));
verifyNotEmpty(testCase, strfind(diffText, ...
    'negate_second_pulse : BOOL := FALSE;'));
verifyEqual(testCase, numel(strfind(diffText, ...
    'tPhase_s >= stParams.settle_time_s')), 2);
verifyEqual(testCase, numel(strfind(diffText, ...
    'tPhase_s >= stParams.pulse_time_s')), 2);
verifyEqual(testCase, numel(strfind(diffText, ...
    'tPhase_s >= stParams.post_time_s')), 1);
verifyNotEmpty(testCase, regexp(diffText, ...
    ['3:\s*IF negate_second_pulse THEN\s*' ...
     'iq_cmd_count_req := -stParams\.max_target_count;\s*ELSE\s*' ...
     'experiment_angle_rad := F_ArchWrap2Pi\(' ...
     'alpha \+ 3\.14159265358979323846\);\s*' ...
     'iq_cmd_count_req := stParams\.max_target_count;'], 'once'));
verifyNotEmpty(testCase, regexp(sequencerText, ...
    ['fbQAxis\s*:\s*FB_DifferentialSweep;[\s\S]*?' ...
     'IF Command\.protocol_id = 3 THEN\s*' ...
     'activeParams\.angle_count := 1;\s*' ...
     'activeParams\.angle_start_rad := 0\.0;\s*' ...
     'activeParams\.angle_step_rad := 0\.0;[\s\S]*?' ...
     'fbQAxis\([\s\S]*?negate_second_pulse := TRUE\);'], 'once'));
verifyNotEmpty(testCase, strfind(sequencerText, ...
    'ELSIF activeProtocolId = 3 THEN'));
end

function testVirtualCstCanonicalizesCopleyAuxiliaryStatusBits(testCase)
repoRoot = fileparts(testCase.TestData.MatlabDir);
kernelText = fileread(fullfile(repoRoot, 'twincat', 'MotorRuntime', 'POUs', ...
    'FB_MotorRuntimeKernel.TcPOU'));
sequencerText = fileread(fullfile(repoRoot, 'twincat', 'ExperimentSequencer', 'POUs', ...
    'FB_ExperimentSequencer.TcPOU'));

% Copley reports these observed states with auxiliary bits 0x1600 and, for
% some states, voltage-enabled bit 4. Both runtime paths must interpret the
% same canonical CiA 402 state bits.
copleyStatus = uint16(hex2dec({'1631', '1633', '1637', '1650', '1670'}));
state006f = bitand(copleyStatus, uint16(hex2dec('006F')));
state004f = bitand(copleyStatus, uint16(hex2dec('004F')));
canonical = zeros(size(copleyStatus), 'uint16');
canonical(state006f == uint16(hex2dec('0021'))) = uint16(hex2dec('0021'));
canonical(state006f == uint16(hex2dec('0023'))) = uint16(hex2dec('0023'));
canonical(state006f == uint16(hex2dec('0027'))) = uint16(hex2dec('0027'));
canonical(state004f == uint16(hex2dec('0040'))) = uint16(hex2dec('0040'));
verifyEqual(testCase, canonical, uint16(hex2dec( ...
    {'0021', '0023', '0027', '0040', '0040'})));

% Public status remains an all-axis reduction during commissioning even
% though private commissioning readiness/fault feedback is selected-axis only.
mixedStatus = uint16(hex2dec({'1637', '0008'}));
selectedAxisFault = bitand(mixedStatus(1), uint16(hex2dec('0008'))) ~= 0;
anyFaultState = any(bitand(mixedStatus, uint16(hex2dec('004F'))) ...
    == uint16(hex2dec('0008')));
verifyFalse(testCase, selectedAxisFault);
verifyTrue(testCase, anyFaultState);

verifyNotEmpty(testCase, strfind(sequencerText, ...
    'MotorFeedback.copley_statusword AND WORD#16#006F'));
verifyNotEmpty(testCase, regexp(sequencerText, ...
    ['ELSIF Command\.lease_id = 0 THEN\s*' ...
     'Command\.last_rejected_request_id := Command\.request_id;\s*' ...
     'Command\.rejection_reason := ''zero lease'';'], 'once'));
verifyNotEmpty(testCase, regexp(kernelText, ...
    ['ELSIF anyFaultState THEN\s*' ...
     'statusStateBits := WORD#16#0008;'], 'once'));
verifyNotEmpty(testCase, strfind(kernelText, ...
    'statusWordAggregate := statusStateBits;'));
verifyEmpty(testCase, strfind(kernelText, 'statusWordCommon'));
verifyEmpty(testCase, strfind(kernelText, 'statusDangerOr'));
end

function testAdsLoggerDryRunDownload(testCase)
client = copley.infra.AdsClient(struct('dryRun', true));
port = copley.infra.AdsLoggerPort(client);
rawLog = port.downloadProtocol(uint16(2));

verifyEqual(testCase, rawLog.protocol_id, uint16(2));
verifyTrue(testCase, rawLog.accepted);
end

function testProtocol1AcceptsMinimumDisplacementWithinRoundoff(testCase)
plan = copley.domain.defaultExperimentPlan(uint32(10));
plan.analysis.protocol1_min_required_dx_m = 5.0e-6;
plan.analysis.protocol1_min_r_squared = 0.80;
rawLog = localProtocol1BoundaryRawLog(5.0e-6 - eps(5.0e-6));

result = copley.analysis.analyzeDifferentialSweep(rawLog, plan);

verifyTrue(testCase, result.accepted);
verifyLessThanOrEqual(testCase, result.quality.max_abs_dx_m, ...
    plan.analysis.protocol1_min_required_dx_m);
end

function testProtocol1AppliesElectricalAngleDirection(testCase)
plan = copley.domain.defaultExperimentPlan(uint32(10));
plan.electrical_angle_sign = int16(-1);
plan.x_ref_m = 0.001;
rawLog = localProtocol1BoundaryRawLog(6.0e-6);
rawLog.rawTable.x_abs_m = rawLog.rawTable.x_abs_m + 0.003;

result = copley.analysis.analyzeDifferentialSweep(rawLog, plan);
xMean = median(double(rawLog.rawTable.x_abs_m));
expected = copley.analysis.wrapTo2Pi(result.theta_e_hat_rad ...
    + 2*pi * (xMean - plan.x_ref_m) / plan.tau_e_m);

verifyTrue(testCase, result.accepted);
verifyEqual(testCase, result.theta_offset_hat_rad, expected, ...
    'AbsTol', 1.0e-12);
end

function testElectricalAngleDirectionRejectsInvalidValues(testCase)
verifyError(testCase, ...
    @()copley.domain.normalizeElectricalAngleSign(-2), ...
    'copley:normalizeElectricalAngleSign:InvalidValue');
verifyError(testCase, ...
    @()copley.domain.normalizeElectricalAngleSign(0), ...
    'copley:normalizeElectricalAngleSign:InvalidValue');
verifyEqual(testCase, copley.domain.normalizeElectricalAngleSign(-1), ...
    int16(-1));
verifyEqual(testCase, copley.domain.normalizeElectricalAngleSign(1), ...
    int16(1));
end

function testProtocol2RejectsIdenticalCommandCurrentPairs(testCase)
plan = copley.domain.defaultExperimentPlan(uint32(9));
plan.protocol2.max_target_count = int16(200);
plan.analysis.protocol2_min_paired_sample_count = 20;
actual = 80 .* ones(30, 1);
rawLog = localProtocol2RawLog(actual, actual);

result = copley.analysis.analyzeIppCurrentRatio(rawLog, plan);

verifyFalse(testCase, result.accepted);
verifyEqual(testCase, result.coarse.current_source, 'iq_cmd_count_req_lreal_A');
verifyEqual(testCase, result.coarse.degenerate_pair_fraction, 1.0);
verifyNotEmpty(testCase, strfind(result.reason, 'degenerate_pair_fraction'));
end

function testProtocol2FallsBackToMeasuredCurrentWhenCommandMissing(testCase)
plan = copley.domain.defaultExperimentPlan(uint32(10));
plan.protocol2.max_target_count = int16(200);
plan.analysis.protocol2_min_paired_sample_count = 20;
actualD = 80 + mod((1:40)', 5);
actualQ = 79 + mod((1:40)', 7);
rawLog = localProtocol2RawLog(actualD, actualQ);
T = rawLog.rawTable;
T.iq_cmd_count_req_lreal(:) = 0.0;
T.target_current_count_lreal(:) = 0.0;
T.output_torque_count(:) = int16(0);
rawLog.rawTable = T;

result = copley.analysis.analyzeIppCurrentRatio(rawLog, plan);
shiftErrorDeg = double(result.coarse.epsilon_samples_rad(:)) * 180/pi ...
    - double(result.coarse.axis_shift_deg);

verifyEqual(testCase, result.coarse.current_source, 'actual_current_A');
verifyLessThan(testCase, result.coarse.degenerate_pair_fraction, 0.95);
verifyGreaterThan(testCase, max(shiftErrorDeg) - min(shiftErrorDeg), 0.1);
verifyTrue(testCase, any(abs(shiftErrorDeg) > 0.01));
end

function testProtocol2PrefersUnquantizedCommandWhenLogged(testCase)
plan = copley.domain.defaultExperimentPlan(uint32(11));
plan.protocol2.max_target_count = int16(200);
plan.analysis.protocol2_min_paired_sample_count = 20;
plan.analysis.protocol2_ramp_delta_tol_count = 1000;
actual = 80 .* ones(40, 1);
rawLog = localProtocol2RawLog(actual, actual);
T = rawLog.rawTable;
qRows = T.phase_id == uint16(10);
dRows = T.phase_id == uint16(11);
T.iq_cmd_count_req_lreal(qRows) = 101.25 + mod((1:sum(qRows))', 17);
T.iq_cmd_count_req_lreal(dRows) = 100.5 + mod((1:sum(dRows))', 17);
T.target_current_count_lreal(qRows) = 20.25 + mod((1:sum(qRows))', 7);
T.target_current_count_lreal(dRows) = 160.5 + mod((1:sum(dRows))', 5);
rawLog.rawTable = T;

result = copley.analysis.analyzeIppCurrentRatio(rawLog, plan);
shiftErrorDeg = double(result.coarse.epsilon_samples_rad(:)) * 180/pi ...
    - double(result.coarse.axis_shift_deg);

verifyEqual(testCase, result.coarse.current_source, 'iq_cmd_count_req_lreal_A');
verifyLessThan(testCase, result.coarse.degenerate_pair_fraction, 0.95);
verifyLessThan(testCase, abs(median(shiftErrorDeg)), 1.0);
end

function testProtocol2UsesConfiguredMeasuredCurrentSource(testCase)
plan = copley.domain.defaultExperimentPlan(uint32(12));
plan.protocol2.max_target_count = int16(200);
plan.analysis.protocol2_min_paired_sample_count = 20;
plan.analysis.protocol2_current_source = 'actual_current_count';
actualD = 80 + mod((1:40)', 5);
actualQ = 79 + mod((1:40)', 7);
rawLog = localProtocol2RawLog(actualD, actualQ);
T = rawLog.rawTable;
T.iq_cmd_count_req_lreal = 100.0 .* ones(height(T), 1);
rawLog.rawTable = T;

result = copley.analysis.analyzeIppCurrentRatio(rawLog, plan);

verifyEqual(testCase, result.coarse.current_source, 'actual_current_A');
verifyTrue(testCase, result.accepted);
verifyLessThan(testCase, result.coarse.degenerate_pair_fraction, 0.95);
end

function testProtocol2RejectsMismatchedLoggedInputCurrent(testCase)
plan = copley.domain.defaultExperimentPlan(uint32(13));
plan.protocol2.max_target_count = int16(200);
plan.analysis.protocol2_min_paired_sample_count = 20;
plan.analysis.protocol2_max_axis_shift_error_deg = 90.0;
plan.analysis.protocol2_ramp_delta_tol_count = 1000;
plan.analysis.protocol2_max_current_equality_mismatch_fraction = 0.20;
actual = 80 .* ones(40, 1);
rawLog = localProtocol2RawLog(actual, actual);
T = rawLog.rawTable;
qRows = T.phase_id == uint16(10);
dRows = T.phase_id == uint16(11);
T.iq_cmd_count_req_lreal(qRows) = 50.0;
T.iq_cmd_count_req_lreal(dRows) = 100.0;
T.target_current_count_lreal = T.iq_cmd_count_req_lreal;
T.output_torque_count = int16(T.target_current_count_lreal);
rawLog.rawTable = T;

result = copley.analysis.analyzeIppCurrentRatio(rawLog, plan);

verifyFalse(testCase, result.accepted);
verifyGreaterThan(testCase, ...
    result.quality.current_equality_mismatch_fraction, 0.20);
verifyNotEmpty(testCase, strfind(result.reason, ...
    'current_equality_mismatch_fraction'));
end

function testQAxisAllowsConfiguredOneSidedResponse(testCase)
plan = copley.domain.defaultExperimentPlan(uint32(8));
plan.analysis.protocol3_min_response_m = 1.0e-7;
plan.analysis.protocol3_allow_one_sided_response = true;
rawLog = struct();
rawLog.protocol_id = uint16(3) .* ones(6, 1, 'uint16');
rawLog.phase_id = uint16([1; 1; 1; 3; 3; 3]);
rawLog.x_abs_m = [0; -2.0e-6; -4.0e-6; 0; -0.05e-6; -0.09e-6];
rawLog.v_actual_mps = zeros(6, 1);

result = copley.analysis.analyzeQAxisVerification(rawLog, plan);

verifyTrue(testCase, result.accepted);
verifyEqual(testCase, result.recommended_q_axis_sign, int16(-1));
verifyTrue(testCase, result.quality.one_sided);
end

function testRunCommissioningMainDryRunSmoke(testCase)
repoRoot = fileparts(testCase.TestData.MatlabDir);
cfgPath = fullfile(repoRoot, 'config', 'copley', ...
    'exp_20260617_131552_sequence.real.local.json');
cfg = copley.infra.readJsonFile(cfgPath);
cfg.baseDir = tempname;
mkdir(cfg.baseDir);
cleanup = onCleanup(@()rmdir(cfg.baseDir, 's'));
result = run_commissioning_main('Config', cfg, ...
    'DryRun', true, 'Verbose', false);

verifyTrue(testCase, result.accepted);
for k = 1:numel(result.protocol_plans)
    verifyEqual(testCase, result.protocol_plans{k}.position_raw_zero, int32(0));
    verifyEqual(testCase, result.protocol_plans{k}.electrical_angle_sign, ...
        int16(1));
    verifyEqual(testCase, result.protocol_plans{k}.calibration_version, uint16(2));
end
verifyEqual(testCase, result.calibration.metadata.electrical_angle_sign, ...
    int16(1));
verifyEqual(testCase, result.calibration.metadata.version, uint16(2));
end

function testMainIsScriptEntryPoint(testCase)
repoRoot = fileparts(testCase.TestData.MatlabDir);
mainText = fileread(fullfile(repoRoot, 'exp00_Commissioning', 'main.m'));
trimmed = strtrim(mainText);

verifyFalse(testCase, strncmp(trimmed, 'function result = main', ...
    length('function result = main')));
verifyNotEmpty(testCase, strfind(mainText, 'run_commissioning_main'));
verifyNotEmpty(testCase, strfind(mainText, 'AllowRealMotion'));
end

function testMagneticPoleLiveScriptIsAxisSelectable(testCase)
repoRoot = fileparts(testCase.TestData.MatlabDir);
scriptText = fileread(fullfile(repoRoot, 'exp00_Commissioning', ...
    'magnetic_pole_commissioning_live.m'));
helperText = fileread(fullfile(repoRoot, 'src', ...
    'run_magnetic_pole_axis.m'));
trimmed = strtrim(scriptText);

verifyFalse(testCase, strncmp(trimmed, ...
    'function result = magnetic_pole_commissioning_live', ...
    length('function result = magnetic_pole_commissioning_live')));
verifyNotEmpty(testCase, strfind(scriptText, 'targetAxisIndex'));
verifyNotEmpty(testCase, strfind(scriptText, ...
    'run_magnetic_pole_axis(targetAxisIndex)'));
verifyEmpty(testCase, strfind(scriptText, 'axisTargets'));
verifyEmpty(testCase, strfind(scriptText, 'writeAcceptedCalibration'));
verifyEmpty(testCase, strfind(scriptText, 'executionMode'));
verifyEmpty(testCase, strfind(scriptText, 'summary'));
verifyNotEmpty(testCase, strfind(scriptText, ...
    'Estimated theta_offset_deg'));
verifyNotEmpty(testCase, strfind(scriptText, ...
    'reference_position_count'));
verifyNotEmpty(testCase, strfind(scriptText, ...
    'reference_commutation_angle'));
verifyNotEmpty(testCase, strfind(scriptText, ...
    'D-axis angle at absolute encoder 0'));
verifyNotEmpty(testCase, strfind(scriptText, 'writeCommissioningArtifacts'));
verifyNotEmpty(testCase, strfind(scriptText, ...
    'copley.analysis.buildThetaResult(result)'));
verifyEmpty(testCase, strfind(scriptText, ...
    'copley.analysis.toSampleTable'));
verifyEmpty(testCase, strfind(scriptText, 'figure('));
verifyNotEmpty(testCase, strfind(scriptText, 'EstimationRejected'));
verifyNotEmpty(testCase, strfind(helperText, 'run_commissioning_main'));
verifyNotEmpty(testCase, strfind(helperText, '''ApplyCalibration'', true'));
verifyNotEmpty(testCase, strfind(helperText, '''Verbose'', false'));
verifyNotEmpty(testCase, strfind(helperText, 'axis_index'));
verifyNotEmpty(testCase, strfind(helperText, '[1 2 3 4]'));
verifyError(testCase, @()run_magnetic_pole_axis(0), ...
    'run_magnetic_pole_axis:InvalidAxisIndex');
verifyError(testCase, @()run_magnetic_pole_axis(5), ...
    'run_magnetic_pole_axis:InvalidAxisIndex');
end

function testMotorRuntimeStatusKeepsPublicAggregateAndPrivateOverrideFeedback(testCase)
repoRoot = fileparts(testCase.TestData.MatlabDir);
sourceText = fileread(fullfile(repoRoot, 'twincat', 'MotorRuntime', 'POUs', ...
    'FB_MotorRuntimeKernel.TcPOU'));
programText = fileread(fullfile(repoRoot, 'twincat', 'MotorRuntime', 'POUs', ...
    'PRG_MotorRuntime.TcPOU'));
useCaseText = fileread(fullfile(testCase.TestData.MatlabDir, '+copley', ...
    '+app', 'CommissioningUseCase.m'));
entryText = fileread(fullfile(testCase.TestData.MatlabDir, ...
    'run_commissioning_main.m'));

verifyEmpty(testCase, strfind(sourceText, ...
    'statusWordAggregate := CopleyStatusWord[axisIndexInt];'));
verifyNotEmpty(testCase, strfind(sourceText, ...
    'feedbackStatusWord := CopleyStatusWord[axisIndexInt];'));
verifyEmpty(testCase, strfind(sourceText, ...
    'allAxesOperationEnabled'));
verifyNotEmpty(testCase, strfind(sourceText, ...
    'minimumStateRank'));
verifyNotEmpty(testCase, strfind(sourceText, ...
    'anyFaultReactionActive'));
verifyNotEmpty(testCase, strfind(sourceText, ...
    'statusWordAggregate := statusStateBits;'));
verifyNotEmpty(testCase, regexp(sourceText, ...
    ['ELSIF anyFaultState THEN\s*' ...
     'statusStateBits := WORD#16#0008;'], 'once'));
verifyEmpty(testCase, strfind(sourceText, ...
    'IF Fault AND NOT copleyFault THEN'));
verifyEmpty(testCase, strfind(sourceText, 'Feedback.fault :='));
verifyNotEmpty(testCase, strfind(sourceText, 'Feedback.fault_id := FaultId;'));
verifyEmpty(testCase, strfind(sourceText, 'driveRequested'));
verifyEmpty(testCase, strfind(sourceText, 'MaxTargetCount'));
verifyEmpty(testCase, strfind(sourceText, 'runtimeUsable'));
verifyNotEmpty(testCase, strfind(sourceText, ...
    'Ready := registeredReferencesValid;'));
verifyNotEmpty(testCase, regexp(sourceText, ...
    ['CopleyControlWord\[i\]\s*:=\s*limitedCommand.ControlWord;\s*' ...
     'IF torqueAxisLinked\[i\] THEN\s*' ...
     'CopleyTargetTorque\[i\]\s*:=\s*limitedCommand.TargetTorque;'], ...
    'once'));
verifyNotEmpty(testCase, strfind(sourceText, ...
    'RegisteredReference[i].reference_position_count'));
verifyNotEmpty(testCase, strfind(sourceText, ...
    'CommissioningReference[i].reference_position_count'));
verifyEmpty(testCase, strfind(sourceText, 'calibrationSourceIndex'));
verifyEmpty(testCase, strfind(sourceText, 'FaultId := 500'));
verifyEmpty(testCase, strfind(programText, 'fbArbiter.Status'));
verifyNotEmpty(testCase, strfind(programText, ...
    'GVL_MotorRuntimeInternal.Feedback.fault_id := fbIoWatchdog.FaultId;'));
verifyEmpty(testCase, strfind(sourceText, ...
    'statusWordAggregate := CopleyStatusWord[1];'));
verifyEmpty(testCase, regexp(sourceText, ...
    ['ELSIF\s*\(NOT overrideRequired\)\s*AND driveRequested\s*' ...
     'AND \(NOT allCalibrationValid\) THEN'], 'once'));
verifyEmpty(testCase, regexp(sourceText, ...
    ['ELSIF\s*\(NOT overrideRequired\)\s*AND driveRequested\s*' ...
     'AND \(NOT allCalibrationAccepted\) THEN'], 'once'));
verifyNotEmpty(testCase, strfind(useCaseText, ...
    'obj.MotorPort.stageReference'));
verifyNotEmpty(testCase, strfind(entryText, ...
    'motorPort.stageReference'));
end

function testThetaResultCapturesAbsolutePositionAnglePair(testCase)
plan = copley.domain.defaultExperimentPlan();
plan.electrical_angle_sign = int16(-1);
plan.position_raw_zero = int32(-12345678);
plan.position_zero_m = 0.002;
plan.x_ref_m = 0.001;
plan.tau_e_m = 0.04;
protocol2 = struct('protocol_id', uint16(2), ...
    'theta_offset_hat_rad', 0.3);
result = struct('protocol_plans', {{plan}}, ...
    'protocol_results', {{protocol2}});

theta = copley.analysis.buildThetaResult(result);
electricalAngleSign = double(plan.electrical_angle_sign);
expected = copley.analysis.wrapTo2Pi(0.3 ...
    + electricalAngleSign * 2*pi * 0.001 / 0.04);
expectedAtEncoderZero = copley.analysis.wrapTo2Pi(expected ...
    - electricalAngleSign * 2*pi * double(plan.position_raw_zero) ...
    * plan.position_m_per_count / plan.tau_e_m);

verifyEqual(testCase, theta.estimation_absolute_position_raw, ...
    int32(-12345678));
verifyEqual(testCase, theta.electrical_angle_sign, int16(-1));
verifyEqual(testCase, theta.theta_at_estimation_rad, expected, ...
    'AbsTol', 1.0e-12);
verifyEqual(testCase, theta.theta_at_estimation_deg, expected * 180/pi, ...
    'AbsTol', 1.0e-12);
verifyEqual(testCase, theta.theta_at_absolute_encoder_zero_rad, ...
    expectedAtEncoderZero, 'AbsTol', 1.0e-12);
verifyEqual(testCase, theta.theta_at_absolute_encoder_zero_deg, ...
    expectedAtEncoderZero * 180/pi, 'AbsTol', 1.0e-10);
end

function testEl5042EncoderZeroAngleIsInvariantAcrossPositions(testCase)
plan = copley.domain.defaultExperimentPlan();
plan.electrical_angle_sign = int16(1);
plan.position_m_per_count = 1.0e-7;
plan.tau_e_m = 0.036;
thetaAtEncoderZero_rad = 1.25;
counts = int32([58868014, 58408617]);

for i = 1:numel(counts)
    thetaAtPosition_rad = copley.analysis.wrapTo2Pi( ...
        thetaAtEncoderZero_rad + 2*pi*double(counts(i))/360000.0);
    protocol2 = struct('protocol_id', uint16(2), ...
        'theta_offset_hat_rad', thetaAtPosition_rad, ...
        'estimation_absolute_position_raw', counts(i), ...
        'estimation_position_m', double(counts(i))*1.0e-7, ...
        'theta_at_estimation_rad', thetaAtPosition_rad);
    result = struct('protocol_plans', {{plan}}, ...
        'protocol_results', {{protocol2}});

    theta = copley.analysis.buildThetaResult(result);

    verifyEqual(testCase, theta.theta_at_absolute_encoder_zero_rad, ...
        thetaAtEncoderZero_rad, 'AbsTol', 1.0e-10);
end
end

function testMotorRuntimeUsesIndependentRegisteredReferenceAbi(testCase)
repoRoot = fileparts(testCase.TestData.MatlabDir);
packerText = fileread(fullfile(testCase.TestData.MatlabDir, '+copley', ...
    '+infra', 'packMotorCalibration.m'));
motorDutText = fileread(fullfile(repoRoot, 'twincat', 'MotorRuntime', 'DUTs', ...
    'DUT_AxisCalibration.TcDUT'));
protocolDutText = fileread(fullfile(repoRoot, 'twincat', 'ExperimentSequencer', ...
    'DUTs', 'DUT_ProtocolParams.TcDUT'));
motorGvlText = fileread(fullfile(repoRoot, 'twincat', 'MotorRuntime', 'GVLs', ...
    'GVL_MotorRuntimeInternal.TcGVL'));
motorKernelText = fileread(fullfile(repoRoot, 'twincat', 'MotorRuntime', 'POUs', ...
    'FB_MotorRuntimeKernel.TcPOU'));

verifyNotEmpty(testCase, strfind(packerText, "zeros(1, 8, 'uint8')"));
verifyNotEmpty(testCase, regexp(motorDutText, ...
    ['reference_position_count\s*:\s*DINT;\s*' ...
     'reference_commutation_angle\s*:\s*UINT;\s*' ...
     'electrical_direction\s*:\s*INT;'], 'once'));
verifyEmpty(testCase, regexp(motorDutText, ...
    '\b(valid|accepted|version)\b', 'once'));
verifyEmpty(testCase, regexp(protocolDutText, ...
    'electrical_angle_sign\s*:', 'once'));
verifyNotEmpty(testCase, strfind(motorKernelText, ...
    'RegisteredReference[i].reference_position_count'));
verifyNotEmpty(testCase, strfind(motorKernelText, ...
    'RegisteredReference[i].reference_commutation_angle'));
verifyNotEmpty(testCase, strfind(motorKernelText, ...
    'RegisteredReference[i].electrical_direction'));
verifyNotEmpty(testCase, strfind(motorKernelText, ...
    'CommissioningReference[i].reference_position_count'));
verifyNotEmpty(testCase, strfind(motorKernelText, ...
    'GVL_MotorRuntimeInternal.COUNTS_PER_ELECTRICAL_PERIOD'));
verifyNotEmpty(testCase, strfind(motorGvlText, ...
    'RegisteredReference : ARRAY [1..AXIS_COUNT]'));
verifyNotEmpty(testCase, strfind(motorGvlText, ...
    ['RegisteredReferenceValid : ARRAY [1..AXIS_COUNT] OF BOOL := ' ...
     '[TRUE, TRUE, TRUE, TRUE]']));
zeroRecords = regexp(motorGvlText, ...
    ['\(reference_position_count\s*:=\s*0,\s*' ...
     'reference_commutation_angle\s*:=\s*0,\s*' ...
     'electrical_direction\s*:=\s*0\)'], 'match');
verifyEmpty(testCase, zeroRecords);
verifyNotEmpty(testCase, strfind(motorGvlText, ...
    'CommissioningReference : ARRAY [1..AXIS_COUNT]'));
verifyNotEmpty(testCase, regexp(motorGvlText, ...
    ['RegisteredReference\s*:\s*ARRAY\s*\[1\.\.AXIS_COUNT\]\s*' ...
     'OF\s*DUT_AxisCalibration\s*:=\s*\[\s*' ...
     '\(reference_position_count\s*:=\s*54984708,\s*' ...
     'reference_commutation_angle\s*:=\s*49480,[\s\S]*?\),\s*' ...
     '\(reference_position_count\s*:=\s*58408617,\s*' ...
     'reference_commutation_angle\s*:=\s*17933,'], 'once'));
verifyNotEmpty(testCase, strfind(motorGvlText, ...
    'reference_position_count := 61902867'));
verifyNotEmpty(testCase, strfind(motorGvlText, ...
    'reference_commutation_angle := 63448'));
verifyNotEmpty(testCase, strfind(motorGvlText, ...
    'reference_position_count := 65824016'));
verifyNotEmpty(testCase, strfind(motorGvlText, ...
    'reference_commutation_angle := 57717'));
verifyNotEmpty(testCase, strfind(motorKernelText, ...
    'AND NOT registeredReferencesValid'));
verifyNotEmpty(testCase, regexp(motorKernelText, ...
    ['AND NOT registeredReferencesValid\s*' ...
     'AND \(\(Command\.ControlWord <> WORD#16#0000\)\s*' ...
     'OR \(Command\.TargetTorque <> 0\)\) THEN'], 'once'));
verifyNotEmpty(testCase, strfind(motorKernelText, ...
    'ELSIF NOT overrideRequired AND Ready AND normalAxisActive[i] THEN'));
verifyEmpty(testCase, strfind(motorKernelText, 'RegisteredReference[1]'));
verifyEmpty(testCase, regexp(motorKernelText, ...
    '\b(valid|accepted|version)\b', 'once'));
end

function testCalibrationDefaultsAndExamplesAreVersionTwoPositiveDirection(testCase)
repoRoot = fileparts(testCase.TestData.MatlabDir);
plan = copley.domain.defaultExperimentPlan();
commissioning = jsondecode(fileread(fullfile(repoRoot, 'config', 'copley', ...
    'commissioning.example.json')));
machine = jsondecode(fileread(fullfile(repoRoot, 'config', 'copley', ...
    'machine.example.json')));

verifyEqual(testCase, plan.electrical_angle_sign, int16(1));
verifyEqual(testCase, plan.calibration_version, uint16(2));
verifyEqual(testCase, commissioning.plan.electrical_angle_sign, 1);
verifyEqual(testCase, commissioning.plan.calibration_version, 2);
verifyEqual(testCase, machine.constants.electrical_angle_sign, 1);
end

function testCommissioningArtifactsAreWrittenWithoutOpenFigures(testCase)
result = run_commissioning_main('DryRun', true, 'Verbose', false);
runDir = tempname;
mkdir(runDir);
dirCleanup = onCleanup(@()rmdir(runDir, 's'));
before = findall(groot, 'Type', 'figure');

copley.analysis.writeCommissioningArtifacts( ...
    result, runDir, 'ShowFigures', false);

after = findall(groot, 'Type', 'figure');
created = setdiff(after, before);
verifyEmpty(testCase, created);
verifyTrue(testCase, exist(fullfile(runDir, 'report.md'), 'file') == 2);
verifyTrue(testCase, exist(fullfile(runDir, 'theta_result.json'), 'file') == 2);
delete(dirCleanup);
end

function testSavedCommissioningResultCanBeReanalyzed(testCase)
baseDir = tempname;
mkdir(baseDir);
cleanup = onCleanup(@()rmdir(baseDir, 's'));
result = run_commissioning_main('DryRun', true, 'Verbose', false);
store = copley.infra.FileRunStore(baseDir);
runDir = store.saveResult(result);

theta = analyze_commissioning_folder(runDir, 'WriteArtifacts', false);

verifyTrue(testCase, exist(fullfile(runDir, 'commissioning_result.mat'), 'file') == 2);
verifyEqual(testCase, theta.accepted, result.accepted);
delete(cleanup);
end

function testReferenceConfigCaptures20260617Run(testCase)
repoRoot = fileparts(testCase.TestData.MatlabDir);
cfgPath = fullfile(repoRoot, 'config', 'copley', ...
    'exp_20260617_164644_sequence.real.local.json');
cfg = jsondecode(fileread(cfgPath));

verifyEqual(testCase, cfg.plan.position_raw_zero, -59057086);
verifyEqual(testCase, cfg.reference.theta_offset_hat_rad, ...
    2.0282189474310579, 'AbsTol', 1.0e-12);
verifyEqual(testCase, cfg.reference.q_axis_sign, 1);
verifyEqual(testCase, cfg.plan.electrical_angle_sign, 1);
verifyEqual(testCase, cfg.plan.protocol2_axis_shift_rad, pi/4, ...
    'AbsTol', 1.0e-12);
verifyEqual(testCase, cfg.analysis.protocol1_theta_reference_rad, ...
    cfg.reference.theta_offset_hat_rad, 'AbsTol', 1.0e-12);
verifyEqual(testCase, cfg.analysis.protocol3_min_response_m, ...
    1.02e-7, 'AbsTol', 1.0e-12);
end

function plan = localPlanWithElectricalAngleSign(value)
plan = copley.domain.defaultExperimentPlan(uint32(55));
plan.electrical_angle_sign = int16(value);
end

function block = localMappingOwnerBlock(projectText, ownerName)
pattern = ['<OwnerB Name="' regexptranslate('escape', ownerName) ...
    '">([\s\S]*?)</OwnerB>'];
match = regexp(projectText, pattern, 'match', 'once');
if isempty(match)
    error('testNewArchitectureUseCases:MissingMappingOwner', ...
        'TwinCAT mapping owner was not found: %s', ownerName);
end
block = match;
end

function manifestFile = localWriteMagneticPoleManifest(axisIndices)
axisTemplate = struct('axis_index', 1, ...
    'reference_position_count', 0, ...
    'reference_commutation_angle', 0, ...
    'electrical_direction', 1);
axes = repmat(axisTemplate, 1, numel(axisIndices));
for i = 1:numel(axisIndices)
    axes(i).axis_index = axisIndices(i);
    axes(i).reference_position_count = 1000 + axisIndices(i);
    axes(i).reference_commutation_angle = 2000 + axisIndices(i);
end
manifest = struct('schema_version', '1.0.0', ...
    'registration_enabled', true, ...
    'counts_per_electrical_period', 360000, ...
    'axes', axes);

manifestFile = [tempname '.json'];
fid = fopen(manifestFile, 'w');
if fid < 0
    error('testNewArchitectureUseCases:ManifestWriteFailed', ...
        'Could not create temporary manifest.');
end
fileCleanup = onCleanup(@()fclose(fid));
fprintf(fid, '%s', jsonencode(manifest));
clear fileCleanup
end

function localVerifyManifestError(testCase, axisIndices, errorId)
manifestFile = localWriteMagneticPoleManifest(axisIndices);
fileCleanup = onCleanup(@()delete(manifestFile));
motor = copley.testing.FakeMotorRuntimePort();
verifyError(testCase, @()register_magnetic_pole_references( ...
    'ManifestFile', manifestFile, 'MotorPort', motor, ...
    'DryRun', true, 'Verbose', false), errorId);
clear fileCleanup
end

function [useCase, ports, plan] = localUseCase()
copley_project_root();
ports = struct();
ports.motor = copley.testing.FakeMotorRuntimePort();
ports.sequencer = copley.testing.FakeSequencerPort();
ports.logger = copley.testing.FakeLoggerPort();
ports.store = copley.testing.FakeRunStore();
ports.clock = copley.testing.FakeClock();
plan = copley.domain.defaultExperimentPlan(uint32(42));
useCase = copley.app.CommissioningUseCase( ...
    ports.motor, ports.sequencer, ports.logger, ports.store, ports.clock);
end

function rawLog = localProtocol2RawLog(actualD, actualQ)
n = numel(actualD);
rows = localProtocol2Rows(2 * n);
sample = 0;
dt = 0.001;
commandCount = int16(80);
for k = 1:n
    sample = sample + 1;
    rows = localProtocol2SetRow(rows, sample, dt, uint16(10), ...
        uint16(0), uint16(k), 0.0, commandCount, int16(actualQ(k)));
    sample = sample + 1;
    rows = localProtocol2SetRow(rows, sample, dt, uint16(11), ...
        uint16(1), uint16(k), -pi/2, commandCount, int16(actualD(k)));
end
rawLog = struct();
rawLog.protocol_id = uint16(2);
rawLog.rawTable = struct2table(rows);
end

function rawLog = localProtocol1BoundaryRawLog(amplitude)
angleCount = 12;
rows = localProtocol1Rows(4 * angleCount);
sample = 0;
dt = 0.001;
for k = 1:angleCount
    angleIndex = uint16(k - 1);
    alpha = double(k - 1) * pi / 6;
    dx = double(amplitude) * cos(alpha);
    [rows, sample] = localProtocol1SetPulse(rows, sample, dt, ...
        angleIndex, alpha, uint16(1), dx, int16(1000));
    [rows, sample] = localProtocol1SetPulse(rows, sample, dt, ...
        angleIndex, alpha, uint16(3), -dx, int16(-1000));
end
rawLog = struct();
rawLog.protocol_id = uint16(1);
rawLog.rawTable = struct2table(rows);
end

function [rows, sample] = localProtocol1SetPulse(rows, sample, dt, ...
        angleIndex, alpha, phaseId, dx, targetCurrentCount)
startSample = sample;
sample = sample + 1;
rows.sample_index(sample, 1) = uint32(sample - 1);
rows.protocol_id(sample, 1) = uint16(1);
rows.phase_id(sample, 1) = phaseId;
rows.angle_index(sample, 1) = angleIndex;
rows.experiment_angle_rad(sample, 1) = alpha;
rows.t_s(sample, 1) = double(sample - 1) * dt;
rows.protocol_t_s(sample, 1) = double(startSample) * dt;
rows.x_abs_m(sample, 1) = 0.0;
rows.target_current_count_lreal(sample, 1) = double(targetCurrentCount);
rows.actual_current_count(sample, 1) = targetCurrentCount;

sample = sample + 1;
rows.sample_index(sample, 1) = uint32(sample - 1);
rows.protocol_id(sample, 1) = uint16(1);
rows.phase_id(sample, 1) = phaseId;
rows.angle_index(sample, 1) = angleIndex;
rows.experiment_angle_rad(sample, 1) = alpha;
rows.t_s(sample, 1) = double(sample - 1) * dt;
rows.protocol_t_s(sample, 1) = double(startSample + 1) * dt;
rows.x_abs_m(sample, 1) = dx;
rows.target_current_count_lreal(sample, 1) = double(targetCurrentCount);
rows.actual_current_count(sample, 1) = targetCurrentCount;
end

function rows = localProtocol1Rows(n)
rows = struct();
rows.sample_index = zeros(n, 1, 'uint32');
rows.protocol_id = zeros(n, 1, 'uint16');
rows.phase_id = zeros(n, 1, 'uint16');
rows.angle_index = zeros(n, 1, 'uint16');
rows.experiment_angle_rad = zeros(n, 1);
rows.t_s = zeros(n, 1);
rows.protocol_t_s = zeros(n, 1);
rows.x_abs_m = zeros(n, 1);
rows.target_current_count_lreal = zeros(n, 1);
rows.actual_current_count = zeros(n, 1, 'int16');
end

function rows = localProtocol2SetRow(rows, sample, dt, phaseId, ...
        angleIndex, localIndex, angleRad, commandCount, actualCurrentCount)
i = sample;
rows.sample_index(i, 1) = uint32(sample - 1);
rows.t_s(i, 1) = double(sample - 1) * dt;
rows.protocol_t_s(i, 1) = rows.t_s(i, 1);
rows.protocol_id(i, 1) = uint16(2);
rows.phase_id(i, 1) = phaseId;
rows.angle_index(i, 1) = angleIndex;
rows.protocol2_local_sample_index(i, 1) = localIndex;
rows.experiment_angle_rad(i, 1) = angleRad;
rows.x_abs_m(i, 1) = 0.0;
rows.x_ref_traj_m(i, 1) = 0.0;
rows.v_est_mps(i, 1) = 0.0;
rows.v_actual_mps(i, 1) = 0.0;
rows.iq_cmd_count_req_lreal(i, 1) = double(commandCount);
rows.target_current_count_lreal(i, 1) = double(commandCount);
rows.output_torque_count(i, 1) = commandCount;
rows.actual_current_count(i, 1) = actualCurrentCount;
end

function rows = localProtocol2Rows(n)
rows = struct();
rows.sample_index = zeros(n, 1, 'uint32');
rows.t_s = zeros(n, 1);
rows.protocol_t_s = zeros(n, 1);
rows.protocol_id = zeros(n, 1, 'uint16');
rows.phase_id = zeros(n, 1, 'uint16');
rows.angle_index = zeros(n, 1, 'uint16');
rows.protocol2_local_sample_index = zeros(n, 1, 'uint16');
rows.experiment_angle_rad = zeros(n, 1);
rows.x_abs_m = zeros(n, 1);
rows.x_ref_traj_m = zeros(n, 1);
rows.v_est_mps = zeros(n, 1);
rows.v_actual_mps = zeros(n, 1);
rows.iq_cmd_count_req_lreal = zeros(n, 1);
rows.target_current_count_lreal = zeros(n, 1);
rows.output_torque_count = zeros(n, 1, 'int16');
rows.actual_current_count = zeros(n, 1, 'int16');
end
