function tr = decode(measurement, job, loggingDelay, tolerance)
%DECODE Validate the existing feedforward_v1 10-by-N capture contract.
% Row 3 is total commanded current [A], NOT measured winding/branch current.
% loggingDelay aligns recorded r/ff only, not the command-to-motion response.
validateattributes(measurement,{'double'},{'2d','real','finite'});
assert(size(measurement,1)==10,'accelff:Schema','Expected 10 measurement rows.');
n = numel(job.r);
for name={'r','f','v','a'}
    validateattributes(job.(name{1}),{'double'},{'column','finite','real','numel',n});
end
assert(size(measurement,2)==n,'accelff:Length','Capture length differs from job.');
validateattributes(loggingDelay,{'double'},{'scalar','integer','nonnegative','<',n});
validateattributes(tolerance,{'double'},{'scalar','finite','positive'});
k = measurement(1,:)';
assert(all(k==fix(k)) && all(diff(k)==1), ...
    'accelff:Counter','Missing, duplicate, or out-of-order logical samples.');
rExpected = [zeros(loggingDelay,1);job.r(1:n-loggingDelay)];
fExpected = [zeros(loggingDelay,1);job.f(1:n-loggingDelay)];
assert(max(abs(measurement(9,:)'-rExpected))<=tolerance, ...
    'accelff:Reference','Recorded reference differs from the requested trajectory.');
assert(max(abs(measurement(7,:)'-fExpected))<=tolerance, ...
    'accelff:Feedforward','Recorded FF differs from the requested waveform.');
assert(max(abs(measurement(2,:)'- ...
    (measurement(9,:)'-measurement(5,:)')))<=tolerance, ...
    'accelff:ErrorSignal','Tracking error does not equal recorded r-y.');
tr = struct('id',string(job.id),'profile_id',string(job.profile_id), ...
    'split',string(job.split),'method',string(job.method),'Ts',job.Ts, ...
    't',(k-k(1))*job.Ts,'counter',k,'r',measurement(9,:)', ...
    'x',measurement(8,:)','y_relative',measurement(5,:)', ...
    'v_raw',measurement(4,:)', ...
    'v_ref',[zeros(loggingDelay,1);job.v(1:n-loggingDelay)], ...
    'a_ref',[zeros(loggingDelay,1);job.a(1:n-loggingDelay)], ...
    'error',measurement(2,:)','current',measurement(3,:)', ...
    'ff',measurement(7,:)','torque_feedback_raw',measurement(6,:)', ...
    'current_kind',"command_A",'quality_passed',false);
end
