function o = options()
%OPTIONS Offline identification thresholds, NOT permission or hardware limits.
% SI units throughout. Changing these values requires a new identification run.
o = struct('velocity_floor',0.002, 'derivative_window',41, ...
    'current_offset_samples',0, 'alignment_reviewed',false, 'minimum_profiles',3, ...
    'minimum_dynamic_profiles',3, 'minimum_observations',6, ...
    'minimum_residual_df',2, 'acceleration_threshold',0.02, ...
    'maximum_condition',1000, 'minimum_partial_leverage',0.02);
end
