function jobs = make_plan(Ts)
%MAKE_PLAN Predeclare condition-level splits. Does not connect to hardware.
validateattributes(Ts,{'double'},{'scalar','positive','finite'});
spec = [2 -2 0; 2 -2 .1; 2 -2 -.1; ...
        3  0 0; 3  0 .1; 3  0 -.1; ...
        4  2 0; 4  2 .1; 4  2 -.1; ...
        3  0 .05; 2.7 1 0; 2.7 1 .05; ...
        3  0 -.05; 3.3 -1 0; 3.3 -1 -.05];
jobs = struct([]);
for k=1:size(spec,1)
    split="train";
    if k>=10, split="validation"; end
    if k>=13, split="test"; end
    p=exp06.profile(Ts,.12,spec(k,1),spec(k,2));
    job=struct('id',sprintf('E06_%02d_r01_t01',k), ...
        'condition_id',sprintf('E06_%02d',k),'profile_id',sprintf('T%.1f_S%+.0f',spec(k,1:2)), ...
        'split',split,'method',"fb",'comparison_label',"FB",'repeat',1,'trial',1, ...
        'Ts',Ts,'origin_m',5.61,'pair',1,'beta',spec(k,3),'ratio',1, ...
        'r',p.r,'v',p.v,'a',p.a,'j',p.j,'f',zeros(size(p.r)));
    jobs(k)=job; %#ok<AGROW>
end
end
