function cfg = local_config_example(root)
%LOCAL_CONFIG_EXAMPLE Copy outside Git or to local_config.local.m, then review.
% This template deliberately CANNOT arm the hardware. NaN is not a default.
% Values below identify the inspected deployment; reverify on the local PC.
cfg=struct('Ts',0.00025,'ams_net_id',"192.168.10.3.1.1",'ads_port',852, ...
    'ads_dll',"C:\Program Files (x86)\Beckhoff\TwinCAT\Functions\TE14xx-ToolsForMatlabAndSimulink\TE141x\NET\TwinCAT.Ads.dll", ...
    'extmode_args',"'192.168.10.3.1.1' 0 16842784", ...
    'encoder_m_per_count',1e-7,'velocity_m_s_per_count',1e-6, ...
    'calibration_manifest',fullfile(root,'config','copley','magnetic_pole_references.json'), ...
    'logging_delay_samples',1,'signal_tolerance',1e-9, ...
    'evaluation_velocity_floor',0.002,'evaluation_acceleration_threshold',0.02,'supervisor_probe',[],'approved_Kd',[]);
% Populate from the reviewed controller, measurement range, site safety
% procedure, and a low-risk unsaturated baseline. Do not choose values merely
% to make assertions pass. current_limit_A MUST equal deployed MAX_INPUT.
names={'current_limit_A','ff_limit_A','ff_slew_A_s','velocity_limit_m_s', ...
    'acceleration_limit_m_s2','jerk_limit_m_s3','tracking_limit_m', ...
    'terminal_limit_m','origin_tolerance_m','idle_velocity_m_s','saturation_margin_A'};
for k=1:numel(names), cfg.(names{k})=NaN; end
cfg.position_limits_m=[NaN,NaN];
end
