function assert_target_built(projectRoot, buildInfoFileName, samplePeriod)
%ASSERT_TARGET_BUILT Require a successful build at the selected sample rate.

buildInfoPath = fullfile( ...
    projectRoot, "config", "data", buildInfoFileName);
if ~isfile(buildInfoPath)
    error("NikonMotor:TargetRebuildRequired", ...
        "No successful target build is recorded in %s. Run the build " + ...
        "section, then publish/install and activate the TwinCAT module.", ...
        buildInfoPath);
end

buildInfo = load(buildInfoPath, "builtSamplePeriod");
if ~isfield(buildInfo, "builtSamplePeriod") || ...
        abs(buildInfo.builtSamplePeriod - samplePeriod) > 1e-12
    error("NikonMotor:TargetRebuildRequired", ...
        "The target was not built at Ts=%.9g s. Run the build section, " + ...
        "then publish/install and activate the TwinCAT module.", ...
        samplePeriod);
end
end
