function log = decode_axis_snapshot(raw, Ts)
%DECODE_AXIS_SNAPSHOT Decode the 20 DWORDs appended to the File Writer record.
% The TC Module input is int32[20]; unsigned fields retain their bit patterns.
assert(isnumeric(raw) && ismatrix(raw) && size(raw,1)==20 && ~isempty(raw), ...
    'NikonMotor:AxisSnapshotSize','Expected 20 rows of axis snapshots.');
assert(all(isfinite(raw),'all') && all(raw==fix(raw),'all') && ...
    all(raw>=double(intmin('int32')) & raw<=double(intmax('int32')),'all'), ...
    'NikonMotor:AxisSnapshotValue','Axis snapshots must contain signed 32-bit integers.');
raw = int32(raw');
cycle = double(typecast(reshape(raw(:,1),[],1),'uint32'));
period = double(typecast(reshape(raw(:,19),[],1),'uint32'))*1e-7;
assert(all(mod(diff(cycle),2^32)==1) && all(abs(period-Ts)<1e-12), ...
    'NikonMotor:AxisSnapshotContinuity','Axis snapshot cycle or period mismatch.');
log = struct('cycle',cycle,'time',(0:size(raw,1)-1)'*Ts, ...
    'position',double(raw(:,2))*1e-7,'velocity',double(raw(:,3))*1e-6, ...
    'virtualCurrent',double(raw(:,4))*2/1000, ...
    'targetCurrent',double(raw(:,5:8))*0.1/1000, ...
    'actualCurrent',double(raw(:,9:12))*0.1/1000, ...
    'statusWord',uint16(raw(:,13:16)), ...
    'fault',double(typecast(reshape(raw(:,17),[],1),'uint32')), ...
    'ioReady',logical(raw(:,18)), ...
    'requestId',typecast(reshape(raw(:,20),[],1),'uint32'), ...
    'source',"simulink_file_writer");
end
