function state = read_tunable_idle_state(Ts)
% Same ADS connection and units as home_to_start; read-only pre/post evidence.
NET.addAssembly(['C:\Program Files (x86)\Beckhoff\TwinCAT\Functions\' ...
    'TE14xx-ToolsForMatlabAndSimulink\TE141x\NET\TwinCAT.Ads.dll']);
ads = TwinCAT.Ads.TcAdsClient;
guard = onCleanup(@()ads.Dispose());
ads.Timeout = 2000;
ads.Connect('192.168.10.3.1.1',852);
adsState = ads.ReadState();
assert(string(adsState.AdsState)=="Run", 'NikonMotor:RuntimeNotRunning', ...
    'TwinCAT must be in Run before checking stage state.');
read = @(name)double(ads.ReadSymbol(ads.ReadSymbolInfo(char(name))));
state = struct('positionCount',read('GVL_MotorRuntime.Status.PositionActualValue'), ...
    'velocity',read('GVL_MotorRuntime.Status.VelocityActualValue'), ...
    'fault',read('GVL_MotorRuntimeInternal.Feedback.fault_id'), ...
    'ioReady',read('PRG_MotorRuntime.fbIoWatchdog.SafeToDrive'), ...
    'taskPeriod',read('PRG_MotorRuntime.taskPeriod_s'), ...
    'targetTorque',read('GVL_MotorRuntime.Command.TargetTorque'));
assert(state.fault==0 && state.ioReady==1 && abs(state.velocity)<=1000 && ...
    state.targetTorque==0 && abs(state.taskPeriod-Ts)<1e-12, ...
    'NikonMotor:StageNotIdle', 'Check stage stop, fault, I/O and task period.');
for axis = 1:4
    state.statusWord(axis) = read(sprintf('PRG_MotorRuntime.copleyStatusWordModule%d',axis));
    state.target(axis) = read(sprintf('PRG_MotorRuntime.copleyTargetTorqueModule%d',axis));
end
assert(all(isfinite([state.statusWord,state.target])) && ...
    all(bitand(uint16(state.statusWord),uint16(12))==0) && all(state.target==0), ...
    'NikonMotor:AxisNotIdle', 'An axis remains enabled, faulted or commanding torque.');
workspace = get_param('linear_exp_tunable_2025a','ModelWorkspace');
for name = ["p_active","p_servo"]
    value = workspace.evalin(name);
    if isa(value,'Simulink.Parameter'), value = value.Value; end
    assert(isequal(value,0), 'NikonMotor:ModelNotIdle', '%s is not zero.',name);
end
end
