function initialIdleSamples = validate_allocation_capture(axisLog,measurement,record)
%VALIDATE_ALLOCATION_CAPTURE Check recorded commands and the unpowered start boundary.
matches = axisLog.requestId==record.requestId;
% File Writer activation can precede the PLC request by several cycles.
% Only a contiguous, unpowered zero-reference prefix may precede the request.
firstAllocated = find(matches,1);
assert(~isempty(firstAllocated),'NikonMotor:AllocationCaptureFailed','No allocated samples recorded.');
initialIdleSamples = firstAllocated-1;
prefix = 1:initialIdleSamples;
matches(prefix) = axisLog.requestId(prefix)==0 & axisLog.virtualCurrent(prefix)==0 & ...
    all(axisLog.targetCurrent(prefix,:)==0,2) & ...
    all(bitand(axisLog.statusWord(prefix,:),uint16(4))==0,2) & measurement(9,prefix)'==0;
assert(numel(axisLog.cycle)==size(measurement,2) && ...
    all(mod(diff(axisLog.cycle),2^32)==1) && all(matches) && ...
    all(abs(diff(axisLog.time)-record.Ts)<1e-9) && ...
    all(axisLog.ioReady) && all(axisLog.fault==0) && ...
    max(abs(axisLog.targetCurrent),[],'all')<=2+1e-6, ...
    'NikonMotor:AllocationCaptureFailed','Incomplete or faulted per-axis capture.');
pair = record.allocation.pair;
expected = axisLog.virtualCurrent.*record.weights;
actual = axisLog.targetCurrent(:,pair:pair+1);
enabled = all(bitand(axisLog.statusWord(:,pair:pair+1),uint16(4))~=0,2);
assert(any(enabled) && max(abs(actual(enabled,:)-expected(enabled,:)),[],'all')<=1.01e-4, ...
    'NikonMotor:AllocationNotApplied','Axis outputs do not match the requested gains.');
end
